import { groundAt } from '../components/scene/bethlehemDimensions';
const eye = (x, z) => [x, groundAt(x, z) + 1.7, z];
const at = (x, z, h = 1) => [x, groundAt(x, z) + h, z];
export const BETHLEHEM = {
  slug: 'bethlehem',
  placeSlug: 'bethlehem-1',
  title: 'Bethlehem',
  subtitle: 'The Nativity · in the days of Herod',
  period: { label: 'c. 6–4 BC · date uncertain', referenceYear: -5 },
  geo: { lat: 31.7043, lon: 35.2075, bearing: 0, xAxis: 90 },
  defaultVantage: 'manger-court',
  defaultEvent: 'birth',
  defaultTimeOfDay: 'night',
  blurb:
    'Walk through a small Judean hill village, from its lamp-lit lanes to a quiet manger and the open fields beyond. Luke follows Mary, Joseph and the shepherds; Matthew tells of visitors from the east and a family’s flight to Egypt. Step into each moment, or explore the village in the changing light.',
  disclaimer:
    'An artist’s reconstruction, not a surveyed plan of ancient Bethlehem. Luke names a manger but does not describe the building. This rock-backed domestic shelter draws on the early cave tradition; the houses, paths, clothing and field locations are conjectural. The Magi’s visit is staged separately in a household courtyard. No exact birth date or astronomical identification of the star is claimed.',
  vantages: [
    {
      id: 'manger-court',
      label: 'At the Manger',
      position: eye(-10, -28),
      lookAt: at(-10, -35, 0.7),
      blurb:
        'A feeding trough is the sign the shepherds are given: a baby wrapped in cloths, lying in a manger. This sheltered space makes room to approach quietly. The Gospel supplies the manger; the room around it is an interpretation.',
      refs: ['Luke 2:6-7', 'Luke 2:12'],
    },
    {
      id: 'village-road',
      label: 'The Road into Bethlehem',
      position: eye(4, 63),
      lookAt: at(-2, 2, 3),
      blurb:
        'Joseph travels from Nazareth to Bethlehem because he belongs to David’s house and family. Mary comes with him. Luke describes the journey and the registration, but does not name their route or say that Mary rode a donkey.',
      refs: ['Luke 2:1-5'],
    },
    {
      id: 'village-well',
      label: 'The Village Well',
      position: eye(-4, 13),
      lookAt: at(-10, 8, 1),
      blurb:
        'Draw near to the domestic life around the story: water jars, woven baskets, courtyards and low houses. This well is part of the imagined village, not an identified well of the Nativity.',
      refs: ['Luke 2:4-7', 'Micah 5:2'],
    },
    {
      id: 'shepherds-field',
      label: 'The Shepherds’ Field',
      position: eye(54, 44),
      lookAt: at(62, 36, 1.5),
      blurb:
        'Outside the village, shepherds watch their flock through the night. Luke does not locate their field. The open hillside here allows the visitor to look from their world back toward Bethlehem.',
      refs: ['Luke 2:8-14'],
    },
    {
      id: 'eastern-overlook',
      label: 'Across the Hills',
      position: eye(79, 73),
      lookAt: at(-12, -25, 6),
      blurb:
        'Look back at the village from the cultivated slopes. The landscape evokes Bethlehem’s limestone hill country; it is not a measured reconstruction of the ancient skyline or the shepherds’ route.',
      refs: ['Luke 2:15-20', 'Micah 5:2'],
    },
    {
      id: 'household-court',
      label: 'The House of the Visit',
      position: eye(15, -34),
      lookAt: at(15, -40, 1),
      blurb:
        'Matthew places the Magi’s visit in a house. Their number and the interval after the birth are not stated. Select their story to see the household courtyard staged for that separate visit.',
      refs: ['Matthew 2:1-12'],
    },
  ],
  events: [
    {
      id: 'arrival',
      label: 'To the City of David',
      place: 'The village road',
      hour: 'dusk',
      position: eye(3, 67),
      lookAt: at(3, 57),
      body: 'Joseph and Mary have come from Nazareth to Bethlehem for the registration described by Luke. Joseph belongs to David’s house and family, and Mary is expecting a child. The route, travel arrangements and exact arrival scene are not given; here the two travelers approach the village on foot.',
      refs: ['Luke 2:1-5'],
    },
    {
      id: 'birth',
      label: 'Laid in a Manger',
      place: 'The domestic shelter',
      hour: 'night',
      position: eye(-10, -28),
      lookAt: at(-10, -35, 0.7),
      body: 'While they are in Bethlehem, Mary gives birth to her firstborn son, wraps him in cloths and lays him in a manger because there is no place for them in the lodging. Joseph stands nearby in this interpretation. Luke does not describe an innkeeper, a separate stable, or the structure of the building. The shelter shown follows a possible domestic setting and the later cave tradition.',
      refs: ['Luke 2:6-7'],
    },
    {
      id: 'good-news',
      label: 'Good News for the Shepherds',
      place: 'The hillside pasture',
      hour: 'night',
      position: eye(53, 43),
      lookAt: at(62, 35, 2),
      body: 'Shepherds keeping watch at night are frightened when an angel appears and the Lord’s glory surrounds them. They hear news of a Savior, Christ the Lord, born in David’s city, and are given the sign of the child in the manger. A heavenly host praises God. The light and single messenger here are a restrained visual interpretation; Luke supplies no description of wings or appearance.',
      refs: ['Luke 2:8-14'],
    },
    {
      id: 'shepherds-visit',
      label: 'Let Us Go to Bethlehem',
      place: 'Beside the manger',
      hour: 'night',
      position: eye(-10, -27.5),
      lookAt: at(-10, -35, 0.8),
      body: 'After the angels leave, the shepherds go quickly to Bethlehem. They find Mary, Joseph and the child in the manger, and tell what they have heard. Mary treasures these things and ponders them. The shepherds return praising God; the Magi are not part of Luke’s scene.',
      refs: ['Luke 2:15-20'],
    },
    {
      id: 'magi-visit',
      label: 'Visitors from the East',
      place: 'A household courtyard',
      hour: 'dusk',
      position: eye(15, -33),
      lookAt: at(15, -40),
      body: 'Matthew tells of Magi who come from the east seeking the king of the Jews. After their audience with Herod, they reach the child and his mother in a house, bow down and offer gold, frankincense and myrrh. The three visitors shown are a compositional choice based on three gifts; Matthew does not count the Magi or say they are kings. The star is an interpretive marker, not a proposed astronomical reconstruction.',
      refs: ['Matthew 2:1-12'],
    },
    {
      id: 'flight',
      label: 'Depart by Night',
      place: 'The road beyond the village',
      hour: 'night',
      position: eye(7, 78),
      lookAt: at(4, 86),
      body: 'After the visitors depart, an angel warns Joseph in a dream to take the child and his mother and escape to Egypt because Herod seeks the child’s life. Joseph gets up and leaves by night. This departure recalls their urgent flight without staging the violence that follows or claiming to trace their exact route.',
      refs: ['Matthew 2:13-15'],
    },
  ],
  hotspots: [
    {
      id: 'feeding-trough',
      label: 'A Manger',
      position: at(-10, -35, 1),
      maxDistance: 22,
      body: 'Luke repeats the manger as a recognizable sign for the shepherds. Its material is not named. This stone feeding trough, bedding and wrapped child are an interpretation of that detail.',
      refs: ['Luke 2:7', 'Luke 2:12', 'Luke 2:16'],
    },
    {
      id: 'david-town',
      label: 'The City of David',
      position: at(-14, 35, 6),
      maxDistance: 110,
      body: 'Luke identifies Bethlehem with David and connects Joseph to David’s family. Micah speaks of a ruler coming from Bethlehem; Matthew cites that prophecy when Herod asks where the Messiah is to be born.',
      refs: ['Luke 2:4', 'Micah 5:2', 'Matthew 2:4-6'],
    },
    {
      id: 'night-watch',
      label: 'Keeping Watch',
      position: at(66, 38, 2),
      maxDistance: 55,
      body: 'The shepherds are at work when the announcement comes. The field and campfire shown here are interpretive scenery. Neither the field’s location nor the season of the birth is supplied by Luke.',
      refs: ['Luke 2:8-14'],
    },
    {
      id: 'gifts',
      label: 'Gold, Frankincense and Myrrh',
      position: at(15, -40, 1),
      maxDistance: 32,
      event: 'magi-visit',
      body: 'Matthew names three gifts and a house. The visitors kneel here in a separate scene, so the village does not combine their visit with the shepherds’ night at the manger.',
      refs: ['Matthew 2:9-12'],
    },
  ],
};
