// Bible Wiki foundation helpers. The foundation asset (people + places with
// their scripture indexes, generated by scripts/build-bible-wiki.js) is
// dynamic-imported so the ~100KB JSON stays out of the initial bundle.

import { CODE_TO_NAME } from './scripture';

let wikiPromise = null;

export function loadBibleWiki() {
  if (!wikiPromise) {
    wikiPromise = import('../assets/bible-wiki.json').then((mod) => normalizeWiki(mod.default));
  }
  return wikiPromise;
}

// Raw asset → { entries, bySlug }. Entry names prefer the display title (`t`)
// so e.g. the record named "Simon" surfaces as "Peter", while `n` stays the
// as-written scripture name.
export function normalizeWiki(raw) {
  const entries = [];
  for (const person of raw.people || []) {
    entries.push({ ...person, type: 'person', name: person.t || person.n });
  }
  for (const place of raw.places || []) {
    entries.push({ ...place, type: 'place', name: place.n });
  }
  return { entries, bySlug: new Map(entries.map((e) => [e.s, e])) };
}

// 'EXO.4' chapter refs → [{ code, book, chapters: [4, 5, …] }] preserving the
// canonical order the asset was written in.
export function groupChaptersByBook(chapterRefs) {
  const groups = [];
  let current = null;
  for (const ref of chapterRefs || []) {
    const [code, chapter] = ref.split('.');
    if (!current || current.code !== code) {
      current = { code, book: CODE_TO_NAME[code] || code, chapters: [] };
      groups.push(current);
    }
    current.chapters.push(Number(chapter));
  }
  return groups;
}

// Entities never auto-highlighted in passage text: "God" appears in a huge
// share of verses and underlining every instance is noise, and "Israel"
// usually means the nation, not the man. Their wiki pages remain reachable
// from the index.
const MATCH_EXCLUDED = new Set(['god_1324', 'israel_682']);

// lowercased single-word name/alias → entry, for tap-to-open in passage text.
// Multi-word names ("Holy Spirit", "Mount Sinai") are skipped — passage text is
// matched token-by-token. When two entries share a name (1,613 scripture names
// are ambiguous) the better-attested one wins.
export function buildNameIndex(entries) {
  const index = new Map();
  const weight = (e) => e.vc || (e.p ? e.p.length : 0);
  const consider = (rawName, entry) => {
    const name = (rawName || '').trim();
    if (!name || name.includes(' ') || name.length < 3) return;
    const key = name.toLowerCase();
    const existing = index.get(key);
    if (!existing || weight(entry) > weight(existing)) index.set(key, entry);
  };
  for (const entry of entries) {
    if (MATCH_EXCLUDED.has(entry.s)) continue;
    consider(entry.n, entry);
    consider(entry.t, entry);
    for (const alias of entry.al || []) consider(alias, entry);
  }
  return index;
}

// BC/AD label for the asset's signed years (negative = BC).
export function formatYear(year) {
  if (!Number.isFinite(year) || year === 0) return null;
  return year < 0 ? `${-year} BC` : `AD ${year}`;
}

// ── Church History (theologians & church fathers) ───────────────────────────
// A sibling dataset to the Bible wiki: post-biblical teachers, hand-curated in
// src/assets/church-teachers.json. Kept separate from the scripture-derived
// foundation — these entries are church history and tradition, not Scripture —
// but they share the same slug-keyed observations and images infrastructure.

export const TEACHER_ERAS = ['Early Church', 'Nicene Era', 'Medieval', 'Reformation', 'Post-Reformation', 'Modern'];

let teachersPromise = null;

export function loadChurchTeachers() {
  if (!teachersPromise) {
    teachersPromise = import('../assets/church-teachers.json').then((mod) => normalizeTeachers(mod.default));
  }
  return teachersPromise;
}

export function normalizeTeachers(raw) {
  const teachers = (raw.teachers || []).map((t) => ({ ...t, type: 'teacher', name: t.n }));
  return { teachers, bySlug: new Map(teachers.map((t) => [t.s, t])) };
}

// Entries with no generated imagery: depicting God or the Holy Spirit
// conflicts with many congregations' convictions, and Jesus is left to each
// org's deliberate choice (manual upload still works for all three).
export const NO_GENERATED_IMAGE = new Set(['god_1324', 'holy_spirit_7400', 'jesus_905']);

// Art direction shared with the batch generator (scripts/wiki-image-prompts.js)
// and consistent with ScriptureImage.jsx.
const IMAGE_STYLE =
  'dignified realistic digital painting, warm natural light, historically accurate ancient Near East, '
  + 'Middle Eastern Semitic people, authentic period clothing and architecture, no anachronisms, '
  + 'no text, no words, no watermark, no halo';

// Generic text-grounded prompt for the in-app admin Generate button. The
// batch script uses richer hand-curated scenes; this covers everything else.
export function buildImagePrompt(entry) {
  if (!entry || NO_GENERATED_IMAGE.has(entry.s)) return null;
  if (entry.type === 'teacher') {
    // Post-biblical figures need period-accurate art, not ancient Near East.
    const base = entry.img
      || `${entry.name}, ${entry.trad || 'a teacher of church history'}, in the setting of their own era`;
    return `${base}, dignified realistic portrait painting, warm natural light, `
      + 'historically accurate period dress and setting, no anachronisms, no text, no words, no watermark, no halo';
  }
  if (entry.type === 'place') {
    return `The biblical place ${entry.name}, an ancient Near Eastern landscape in the biblical era, `
      + `historically plausible terrain and settlement, ${IMAGE_STYLE}`;
  }
  const era = entry.y
    ? (entry.y[0] === entry.y[1]
      ? formatYear(entry.y[0])
      : [formatYear(entry.y[0]), formatYear(entry.y[1])].filter(Boolean).join(' to '))
    : null;
  const person = entry.g === 'F' ? 'a woman of the Bible' : entry.g === 'M' ? 'a man of the Bible' : 'a figure of the Bible';
  return `Reverent portrait of ${entry.name}, ${person}${era ? ` who lived around ${era}` : ''}, `
    + `in authentic ancient Near Eastern dress of the biblical era, ${IMAGE_STYLE}`;
}
