// Bible Wiki foundation helpers. The foundation asset (people + places with
// their scripture indexes, generated by scripts/build-bible-wiki.js) is
// dynamic-imported so the ~100KB JSON stays out of the initial bundle.

import { CODE_TO_NAME } from './scripture';

let wikiPromise = null;

export function loadBibleWiki() {
  if (!wikiPromise) {
    wikiPromise = import('../assets/bible-wiki.json').then((mod) => normalizeWiki(mod.default));
  }
  return wikiPromise;
}

// Raw asset → { entries, bySlug }. Entry names prefer the display title (`t`)
// so e.g. the record named "Simon" surfaces as "Peter", while `n` stays the
// as-written scripture name.
export function normalizeWiki(raw) {
  const entries = [];
  for (const person of raw.people || []) {
    entries.push({ ...person, type: 'person', name: person.t || person.n });
  }
  for (const place of raw.places || []) {
    entries.push({ ...place, type: 'place', name: place.n });
  }
  return { entries, bySlug: new Map(entries.map((e) => [e.s, e])) };
}

// 'EXO.4' chapter refs → [{ code, book, chapters: [4, 5, …] }] preserving the
// canonical order the asset was written in.
export function groupChaptersByBook(chapterRefs) {
  const groups = [];
  let current = null;
  for (const ref of chapterRefs || []) {
    const [code, chapter] = ref.split('.');
    if (!current || current.code !== code) {
      current = { code, book: CODE_TO_NAME[code] || code, chapters: [] };
      groups.push(current);
    }
    current.chapters.push(Number(chapter));
  }
  return groups;
}

// Entities never auto-highlighted in passage text: "God" appears in a huge
// share of verses and underlining every instance is noise, and "Israel"
// usually means the nation, not the man. Their wiki pages remain reachable
// from the index.
const MATCH_EXCLUDED = new Set(['god_1324', 'israel_682']);

// lowercased single-word name/alias → entry, for tap-to-open in passage text.
// Multi-word names ("Holy Spirit", "Mount Sinai") are skipped — passage text is
// matched token-by-token. When two entries share a name (1,613 scripture names
// are ambiguous) the better-attested one wins.
export function buildNameIndex(entries) {
  const index = new Map();
  const weight = (e) => e.vc || (e.p ? e.p.length : 0);
  const consider = (rawName, entry) => {
    const name = (rawName || '').trim();
    if (!name || name.includes(' ') || name.length < 3) return;
    const key = name.toLowerCase();
    const existing = index.get(key);
    if (!existing || weight(entry) > weight(existing)) index.set(key, entry);
  };
  for (const entry of entries) {
    if (MATCH_EXCLUDED.has(entry.s)) continue;
    consider(entry.n, entry);
    consider(entry.t, entry);
    for (const alias of entry.al || []) consider(alias, entry);
  }
  return index;
}

// BC/AD label for the asset's signed years (negative = BC).
export function formatYear(year) {
  if (!Number.isFinite(year) || year === 0) return null;
  return year < 0 ? `${-year} BC` : `AD ${year}`;
}
