// Bible Wiki foundation helpers. The foundation assets (people + places with
// their scripture indexes, generated by scripts/build-bible-wiki.js) are
// dynamic-imported so the JSON stays out of the initial bundle:
//   bible-wiki.json          — core set (~380 entries): powers the app-wide
//                              entity linker and the wiki's first paint.
//   bible-wiki-extended.json — the long tail (~4,000 entries): loaded only
//                              when browsing/searching the wiki or opening an
//                              extended slug.
//   bible-events.json        — biblical events in narrative order.
//   bible-wiki-curated.json  — hand-curated enrichments (name meanings, story
//                              arcs, key verses) merged onto entries by slug.

import { CODE_TO_NAME } from './scripture';
import { registerDynamicPlans } from './readingPlans';

let wikiPromise = null;
let fullPromise = null;
let eventsPromise = null;

// Curated fields are merged onto the raw entry; `al` merges (curated aliases
// append), everything else overrides.
export function applyCurated(raw, curated) {
  if (!curated) return raw;
  const merge = (list) => (list || []).map((e) => {
    const extra = curated[e.s];
    if (!extra) return e;
    const merged = { ...e, ...extra };
    if (extra.al && e.al) merged.al = [...new Set([...e.al, ...extra.al])];
    return merged;
  });
  return { people: merge(raw.people), places: merge(raw.places) };
}

export function loadBibleWiki() {
  if (!wikiPromise) {
    wikiPromise = Promise.all([
      import('../assets/bible-wiki.json'),
      import('../assets/bible-wiki-curated.json'),
    ]).then(([mod, curated]) => normalizeWiki(applyCurated(mod.default, curated.default)));
  }
  return wikiPromise;
}

// Core + extended + events, merged. Entries order: core first (already
// weight-ranked), then the long tail. Events live in bySlug (so /wiki/:slug
// resolves them) and in `events`, but not in `entries`.
export function loadBibleWikiFull() {
  if (!fullPromise) {
    fullPromise = Promise.all([
      loadBibleWiki(),
      import('../assets/bible-wiki-extended.json'),
      import('../assets/bible-wiki-curated.json'),
      loadBibleEvents(),
    ]).then(([core, extMod, curated, events]) => {
      const ext = normalizeWiki(applyCurated(extMod.default, curated.default));
      const entries = [...core.entries, ...ext.entries];
      const bySlug = new Map(entries.map((e) => [e.s, e]));
      for (const ev of events.events) bySlug.set(ev.s, ev);
      return { entries, bySlug, events: events.events, coreCount: core.entries.length };
    });
  }
  return fullPromise;
}

export function loadBibleEvents() {
  if (!eventsPromise) {
    eventsPromise = import('../assets/bible-events.json').then((mod) => {
      const events = (mod.default.events || []).map((e) => ({ ...e, type: 'event', name: e.n }));
      return { events, bySlug: new Map(events.map((e) => [e.s, e])) };
    });
  }
  return eventsPromise;
}

// Raw asset → { entries, bySlug }. Entry names prefer the display title (`t`)
// so e.g. the record named "Simon" surfaces as "Peter", while `n` stays the
// as-written scripture name.
export function normalizeWiki(raw) {
  const entries = [];
  for (const person of raw.people || []) {
    entries.push({ ...person, type: 'person', name: person.t || person.n });
  }
  for (const place of raw.places || []) {
    entries.push({ ...place, type: 'place', name: place.n });
  }
  return { entries, bySlug: new Map(entries.map((e) => [e.s, e])) };
}

// 'EXO.4' chapter refs → [{ code, book, chapters: [4, 5, …] }] preserving the
// canonical order the asset was written in.
export function groupChaptersByBook(chapterRefs) {
  const groups = [];
  let current = null;
  for (const ref of chapterRefs || []) {
    const [code, chapter] = ref.split('.');
    if (!current || current.code !== code) {
      current = { code, book: CODE_TO_NAME[code] || code, chapters: [] };
      groups.push(current);
    }
    current.chapters.push(Number(chapter));
  }
  return groups;
}

// Entries never auto-highlighted in passage text. god_1324 is excluded
// entirely ("God" appears in a huge share of verses). Name-level exclusions
// let an entry keep its other aliases linkable: "Israel" usually means the
// nation rather than the patriarch, but his alias "Jacob" still links.
export const MATCH_EXCLUDED = new Set(['god_1324']);
export const MATCH_EXCLUDED_NAMES = new Set(['god', 'israel', 'lord']);

// lowercased single-word name/alias → entry, for tap-to-open in passage text.
// Multi-word names ("Holy Spirit", "Mount Sinai") are skipped — passage text is
// matched token-by-token. When two entries share a name (1,613 scripture names
// are ambiguous) the better-attested one wins.
export function buildNameIndex(entries) {
  const index = new Map();
  const weight = (e) => e.vc || (e.p ? e.p.length : 0);
  const consider = (rawName, entry) => {
    const name = (rawName || '').trim();
    if (!name || name.includes(' ') || name.length < 3) return;
    const key = name.toLowerCase();
    if (MATCH_EXCLUDED_NAMES.has(key)) return;
    const existing = index.get(key);
    if (!existing || weight(entry) > weight(existing)) index.set(key, entry);
  };
  for (const entry of entries) {
    if (MATCH_EXCLUDED.has(entry.s)) continue;
    consider(entry.n, entry);
    consider(entry.t, entry);
    for (const alias of entry.al || []) consider(alias, entry);
  }
  return index;
}

// BC/AD label for the asset's signed years (negative = BC).
export function formatYear(year) {
  if (!Number.isFinite(year) || year === 0) return null;
  return year < 0 ? `${-year} BC` : `AD ${year}`;
}

export function formatYearRange(y) {
  if (!y) return null;
  if (y[0] === y[1]) return formatYear(y[0]);
  return [formatYear(y[0]), formatYear(y[1])].filter(Boolean).join(' – ');
}

// ── Chapter index & derived views ───────────────────────────────────────────

// Map<'GEN.12', entry[]> across the given entries (people + places), each
// chapter's entities sorted best-attested first.
export function buildChapterIndex(entries) {
  const index = new Map();
  for (const entry of entries) {
    for (const ref of entry.p || []) {
      let list = index.get(ref);
      if (!list) { list = []; index.set(ref, list); }
      list.push(entry);
    }
  }
  const weight = (e) => e.vc || (e.p ? e.p.length : 0);
  for (const list of index.values()) list.sort((a, b) => weight(b) - weight(a));
  return index;
}

// Unique entities appearing in any of the given chapter ids ('GEN.12'), best
// attested first. Each result is { entry, firstHere } — firstHere marks a
// first appearance in Scripture (the entry's first verse falls in one of
// these chapters).
export function entitiesForChapters(chapterIndex, chapterIds) {
  const seen = new Set();
  const out = [];
  const chapters = new Set(chapterIds || []);
  for (const id of chapterIds || []) {
    for (const entry of chapterIndex.get(id) || []) {
      if (seen.has(entry.s)) continue;
      seen.add(entry.s);
      const fvChapter = entry.fv ? entry.fv.split('.').slice(0, 2).join('.') : null;
      out.push({ entry, firstHere: !!fvChapter && chapters.has(fvChapter) });
    }
  }
  const weight = (e) => e.vc || (e.p ? e.p.length : 0);
  return out.sort((a, b) => weight(b.entry) - weight(a.entry));
}

// Entries that share the most chapters with `entry` — "often appears with".
export function coOccurring(entry, entries, limit = 8) {
  const mine = new Set(entry.p || []);
  if (!mine.size) return [];
  const scored = [];
  for (const other of entries) {
    if (other.s === entry.s || MATCH_EXCLUDED.has(other.s)) continue;
    let shared = 0;
    for (const ref of other.p || []) if (mine.has(ref)) shared += 1;
    if (shared >= 2) scored.push({ entry: other, shared });
  }
  return scored
    .sort((a, b) => b.shared - a.shared || (b.entry.vc || 0) - (a.entry.vc || 0))
    .slice(0, limit);
}

// Lexical relevance search over wiki entries (people/places/events/teachers).
// Complements verse-embedding search: "who was melchizedek" should surface the
// wiki page, not just verses. Name/alias matches dominate; descriptions catch
// paraphrases ("swallowed by a fish" → Jonah's desc).
export function searchWikiEntries(query, entries, limit = 5) {
  const q = (query || '').trim().toLowerCase();
  if (q.length < 3) return [];
  const qWords = q.split(/\s+/).filter((w) => w.length >= 3);
  const scored = [];
  for (const entry of entries) {
    const name = entry.name.toLowerCase();
    const names = [name, (entry.n || '').toLowerCase(), ...(entry.al || []).map((a) => a.toLowerCase())];
    let score = 0;
    if (names.some((n) => n === q)) score = 100;
    else if (names.some((n) => q.includes(n) && n.length >= 4)) score = 80;
    else if (names.some((n) => n.startsWith(q))) score = 70;
    else if (qWords.some((w) => names.some((n) => n === w))) score = 65;
    else if (names.some((n) => n.includes(q))) score = 50;
    const desc = (entry.desc || entry.sum || '').toLowerCase();
    if (desc && qWords.length) {
      const hits = qWords.filter((w) => desc.includes(w)).length;
      score += Math.min(30, hits * (10 + (hits === qWords.length ? 5 : 0)));
    }
    if (score >= 30) scored.push({ entry, score });
  }
  const weight = (e) => e.vc || (e.p ? e.p.length : 0);
  return scored
    .sort((a, b) => b.score - a.score || weight(b.entry) - weight(a.entry))
    .slice(0, limit)
    .map((s) => s.entry);
}

// Deterministic "figure of the week" — same pick for everyone all week.
export function weeklyPick(list, now = new Date(), salt = 0) {
  if (!list?.length) return null;
  const week = Math.floor((now.getTime() / 86400000 + 4) / 7); // epoch weeks, Monday-ish aligned
  return list[(week + salt) % list.length];
}

// ── Character reading plans ─────────────────────────────────────────────────
// Any wiki entry's chapter index IS a reading plan. Plans are registered into
// the readingPlans dynamic registry under 'wiki-<slug>' so enrollments persist
// and resume like any built-in plan.

export const WIKI_PLAN_PREFIX = 'wiki-';
export const wikiPlanId = (slug) => `${WIKI_PLAN_PREFIX}${slug}`;

export function buildWikiPlan(entry) {
  const chapters = entry.p || [];
  if (chapters.length < 2) return null;
  const isPerson = entry.type === 'person';
  return {
    id: wikiPlanId(entry.s),
    name: isPerson ? `The Life of ${entry.name}` : `${entry.name} in Scripture`,
    description: isPerson
      ? `Every chapter where ${entry.name} appears, in canonical order — ${chapters.length} chapters.`
      : `Every chapter that mentions ${entry.name}, in canonical order — ${chapters.length} chapters.`,
    category: 'character',
    paceLabel: '1 chapter/day',
    days: chapters.length,
    chapters,
    wikiSlug: entry.s,
  };
}

let wikiPlansRegistered = false;

// Registers a reading plan for every core + extended entry with ≥2 chapters.
// Called lazily: from wiki pages before offering the button, and from
// useReadingPlan when an enrollment with a 'wiki-' plan id is found.
export async function ensureWikiPlans() {
  if (wikiPlansRegistered) return;
  const full = await loadBibleWikiFull();
  const plans = [];
  for (const entry of full.entries) {
    const plan = buildWikiPlan(entry);
    if (plan) plans.push(plan);
  }
  registerDynamicPlans(plans);
  wikiPlansRegistered = true;
}

// ── Church History (theologians & church fathers) ───────────────────────────
// A sibling dataset to the Bible wiki: post-biblical teachers, councils, and
// creeds, hand-curated in src/assets/church-teachers.json. Kept separate from
// the scripture-derived foundation — these entries are church history and
// tradition, not Scripture — but they share the same slug-keyed observations
// and images infrastructure.

export const TEACHER_ERAS = ['Early Church', 'Nicene Era', 'Medieval', 'Reformation', 'Post-Reformation', 'Modern'];

let teachersPromise = null;

export function loadChurchTeachers() {
  if (!teachersPromise) {
    teachersPromise = import('../assets/church-teachers.json').then((mod) => normalizeTeachers(mod.default));
  }
  return teachersPromise;
}

export function normalizeTeachers(raw) {
  const teachers = (raw.teachers || []).map((t) => ({ ...t, type: 'teacher', name: t.n }));
  return { teachers, bySlug: new Map(teachers.map((t) => [t.s, t])) };
}

// Teachers who list `slug` among the Bible figures they especially taught
// from — rendered on that figure's wiki page as "Voices from church history".
export function teachersForBibleFigure(teachers, slug) {
  return teachers.filter((t) => (t.bib || []).includes(slug));
}

// Reverse of `infl` — teachers influenced BY this one.
export function influencedBy(teachers, slug) {
  return teachers.filter((t) => (t.infl || []).includes(slug));
}

// Entries with no generated imagery: depicting God or the Holy Spirit
// conflicts with many congregations' convictions, and Jesus is left to each
// org's deliberate choice (manual upload still works for all three).
export const NO_GENERATED_IMAGE = new Set(['god_1324', 'holy_spirit_7400', 'jesus_905']);

// Art direction shared with the batch generator (scripts/wiki-image-prompts.js)
// and consistent with ScriptureImage.jsx.
const IMAGE_STYLE =
  'dignified realistic digital painting, warm natural light, historically accurate ancient Near East, '
  + 'Middle Eastern Semitic people, authentic period clothing and architecture, no anachronisms, '
  + 'no text, no words, no watermark, no halo';

// Generic text-grounded prompt for the in-app admin Generate button. The
// batch script uses richer hand-curated scenes; this covers everything else.
export function buildImagePrompt(entry) {
  if (!entry || NO_GENERATED_IMAGE.has(entry.s)) return null;
  if (entry.type === 'teacher') {
    if (entry.kind === 'creed' || entry.kind === 'council') {
      return `${entry.name}, an assembly of early church elders and scribes with manuscripts, `
        + 'dignified realistic historical painting, warm candlelight, historically accurate period dress '
        + 'and architecture, no anachronisms, no text, no words, no watermark, no halo';
    }
    // Post-biblical figures need period-accurate art, not ancient Near East.
    const base = entry.img
      || `${entry.name}, ${entry.trad || 'a teacher of church history'}, in the setting of their own era`;
    return `${base}, dignified realistic portrait painting, warm natural light, `
      + 'historically accurate period dress and setting, no anachronisms, no text, no words, no watermark, no halo';
  }
  if (entry.type === 'place') {
    return `The biblical place ${entry.name}, an ancient Near Eastern landscape in the biblical era, `
      + `historically plausible terrain and settlement, ${IMAGE_STYLE}`;
  }
  if (entry.type === 'event') {
    return `${entry.name}, a scene from the Bible, ${IMAGE_STYLE}`;
  }
  const era = entry.y ? formatYearRange(entry.y) : null;
  const person = entry.g === 'F' ? 'a woman of the Bible' : entry.g === 'M' ? 'a man of the Bible' : 'a figure of the Bible';
  return `Reverent portrait of ${entry.name}, ${person}${era ? ` who lived around ${era}` : ''}, `
    + `in authentic ancient Near Eastern dress of the biblical era, ${IMAGE_STYLE}`;
}
