// Two-sentence book introductions shown once, in DailyReading, the first
// time a plan's schedule enters a new book — a small orientation moment so
// (for example) the wall of Leviticus doesn't land with zero context.
export const BOOK_INTROS = {
  GEN: 'Genesis opens the story of everything: creation, the fall, the flood, and the call of Abraham’s family. It ends with that family in Egypt, waiting for the story to continue.',
  EXO: 'Exodus tells how God rescues Israel from slavery in Egypt and forms them into a covenant people at Mount Sinai. Along the way come the Ten Commandments and the plans for the tabernacle.',
  LEV: 'Leviticus is a priestly manual for how a holy God can dwell among an unholy people — sacrifices, purity, and the calendar of feasts. It reads like law, but it’s really about access to God.',
  NUM: 'Numbers follows Israel’s decades of wandering between Sinai and the promised land, marked by two censuses (the "numbering") and repeated failures of trust. It’s a book about a generation that almost didn’t make it.',
  DEU: 'Deuteronomy is Moses’ farewell address, restating the law for the generation about to enter Canaan. Its core command — love the Lord your God — is quoted by Jesus as the greatest commandment.',
  JOS: 'Joshua recounts Israel’s conquest and settlement of the promised land under Moses’ successor. It closes with a covenant renewal and Joshua’s challenge to choose whom to serve.',
  JDG: 'Judges cycles through Israel’s repeated pattern of unfaithfulness, oppression, deliverance, and relapse in the era before kings. Its refrain — "everyone did what was right in their own eyes" — sets up the need for a king.',
  RUT: 'Ruth is a short, tender story of loyalty and redemption set during the judges, following a Moabite widow who becomes King David’s great-grandmother. It’s a quiet counter-story to the chaos around it.',
  '1SA': '1 Samuel tells of the last judge Samuel, Israel’s first king Saul, and the rise of young David. It traces how power shifts from a failing king to a shepherd chosen by God.',
  '2SA': '2 Samuel follows David’s reign — his triumphs, his covenant promise of an eternal throne, and his devastating moral failures. It’s as honest about David’s sin as it is about his faith.',
  '1KI': '1 Kings covers Solomon’s golden reign and temple-building, then the kingdom’s split into Israel and Judah. Elijah’s confrontations with Baal worship dominate its second half.',
  '2KI': '2 Kings tracks the decline and eventual fall of both Israel and Judah, ending in exile. Prophets like Elisha keep pointing kings back to covenant faithfulness, largely in vain.',
  '1CH': '1 Chronicles retells Israel’s history from Adam through David for a post-exilic audience, opening with long genealogies that establish identity after exile. Its focus is David’s preparation for the temple.',
  '2CH': '2 Chronicles parallels Kings but centers on Judah’s temple and Davidic kings, ending with the exile and a note of hope for return. It’s history written to explain why worship matters.',
  EZR: 'Ezra narrates the return from Babylonian exile and the rebuilding of the temple, then the priest Ezra’s reforms. It’s a story of a scattered people re-forming around God’s law.',
  NEH: 'Nehemiah continues the return story with the rebuilding of Jerusalem’s walls against fierce opposition. It pairs practical leadership with a renewed public commitment to the covenant.',
  EST: 'Esther tells how a Jewish queen in the Persian court risks everything to save her people from genocide. God is never named, yet his providence runs through every turn of the plot.',
  JOB: 'Job wrestles with why the righteous suffer, framed by a wager in the heavenly court and Job’s long dialogue with friends who blame him. God’s answer, when it comes, reframes the question entirely.',
  PSA: 'Psalms is Israel’s songbook and prayer book — 150 poems of praise, lament, thanksgiving, and hope. They give language to nearly every emotion a person brings before God.',
  PRO: 'Proverbs collects short, memorable sayings for living wisely, framed as a father’s instruction to a son. Its recurring theme: "the fear of the Lord is the beginning of wisdom."',
  ECC: 'Ecclesiastes is the Teacher’s honest search for meaning "under the sun," testing pleasure, work, and wisdom and finding them all fleeting. It ends by pointing past that emptiness to fearing God.',
  SNG: 'Song of Solomon is a lyric poem celebrating love and desire between a bride and groom. Read across history as both a love poem and a picture of covenant love between God and his people.',
  ISA: 'Isaiah spans warnings of judgment on Judah and the nations, promises of a coming Messiah, and visions of restoration and a new creation. It’s the most-quoted Old Testament book in the New.',
  JER: 'Jeremiah is the "weeping prophet," called to warn Judah of coming judgment even as he grieves it. His book also holds one of the Old Testament’s clearest promises of a coming new covenant.',
  LAM: 'Lamentations is a set of funeral poems mourning Jerusalem’s destruction, written with careful acrostic structure even in raw grief. At its center sits a startling turn toward hope: "his mercies are new every morning."',
  EZK: 'Ezekiel prophesies from exile in Babylon, using vivid symbolic visions — a valley of dry bones, a new temple — to announce both judgment and restoration. It insists God’s glory hasn’t abandoned his people, even in exile.',
  DAN: 'Daniel pairs court stories of faithfulness under pressure (the lions’ den, the fiery furnace) with apocalyptic visions of empires and a coming kingdom that will outlast them all. It’s a book about integrity in exile.',
  HOS: 'Hosea uses the prophet’s own painful marriage to an unfaithful wife as a living picture of Israel’s unfaithfulness to God. Yet its refrain is relentless: God’s love pursues even after betrayal.',
  JOL: 'Joel responds to a locust plague as a preview of the coming "day of the Lord," calling Israel to repentance. It contains the promise of God’s Spirit poured out on all people, later quoted at Pentecost.',
  AMO: 'Amos, a shepherd from Judah, confronts the northern kingdom’s complacent wealth and injustice toward the poor. His famous cry: "let justice roll on like a river."',
  OBA: 'Obadiah, the Old Testament’s shortest book, pronounces judgment on Edom for gloating over Judah’s downfall. Its point: pride and cruelty toward the vulnerable will not go unanswered.',
  JON: 'Jonah is the reluctant prophet who runs from God’s call to preach to Nineveh, gets swallowed by a great fish, and still resents God’s mercy when the city repents. It’s a story about the size of God’s compassion versus the smallness of ours.',
  MIC: 'Micah confronts injustice among Judah’s leaders while promising a coming ruler born in Bethlehem. Its summary of true religion is one of Scripture’s best known: act justly, love mercy, walk humbly.',
  NAM: 'Nahum announces the fall of Nineveh, the same city Jonah once saw spared — its cruelty has caught up with it. It balances God’s patience with his justice.',
  HAB: 'Habakkuk is a dialogue between the prophet and God, wrestling with why evil seems to prosper. It resolves not with an answer to "why" but a decision: "the righteous will live by faith."',
  ZEP: 'Zephaniah warns of a coming day of judgment on Judah and the nations, then turns to a promise of restoration and God rejoicing over his people with singing. Judgment and joy sit side by side.',
  HAG: 'Haggai prods the returned exiles to stop delaying and finish rebuilding the temple. His message: put God’s house first, and blessing follows.',
  ZEC: 'Zechariah encourages the same rebuilding generation with night visions and prophecies of a coming king "righteous and having salvation, gentle and riding on a donkey." Much of it points forward to the Messiah.',
  MAL: 'Malachi, the last Old Testament voice, confronts a spiritually apathetic post-exilic community and promises a messenger to prepare the way before the Lord. It closes the Old Testament looking forward to what comes next.',
  MAT: 'Matthew presents Jesus as the promised Jewish Messiah, tracing his lineage to David and Abraham and organizing his teaching into five great discourses, including the Sermon on the Mount. It ends with the Great Commission.',
  MRK: 'Mark is the shortest, fastest-paced Gospel, presenting Jesus as the suffering Servant who came "to serve, and to give his life as a ransom for many." Action moves quickly toward the cross.',
  LUK: 'Luke, written by a Gentile physician, emphasizes Jesus’ compassion for the outcast, the poor, and the marginalized, with careful historical detail. It’s the first half of a two-part work continued in Acts.',
  JHN: 'John presents Jesus as the eternal Word made flesh, structured around seven miraculous "signs" and seven "I am" statements. Its stated purpose: "that you may believe that Jesus is the Messiah."',
  ACT: 'Acts continues Luke’s Gospel, tracing the Holy Spirit-empowered spread of the church from Jerusalem to Rome through Peter, then Paul. It’s the origin story of the early church’s mission.',
  ROM: 'Romans is Paul’s most systematic letter, laying out humanity’s need for the gospel, justification by faith, and life in the Spirit. It has shaped Christian theology more than perhaps any other New Testament book.',
  '1CO': '1 Corinthians addresses a fractured, troubled church — divisions, immorality, lawsuits, worship disorder — with pastoral directness. Its heart is chapter 13’s portrait of love and chapter 15’s defense of the resurrection.',
  '2CO': '2 Corinthians is Paul’s most personal letter, defending his apostleship and ministry against critics while reflecting on weakness, suffering, and reconciliation. "My grace is sufficient for you" comes from here.',
  GAL: 'Galatians is Paul’s fiery defense of salvation by faith alone against teachers requiring the law for Gentile believers. "It is for freedom that Christ has set us free" is its rallying cry.',
  EPH: 'Ephesians describes the church as the body of Christ, united across Jew-Gentile lines by grace, then works out what that unity looks like in everyday relationships. Grace and practical ethics are held tightly together.',
  PHP: 'Philippians, written from prison, is Paul’s letter of joy — urging contentment and unity while pointing to Christ’s humility as the pattern for Christian life. "To live is Christ, to die is gain."',
  COL: 'Colossians proclaims the supremacy of Christ over every rival philosophy and power, then draws out what a life "hidden with Christ" looks like. It closely parallels Ephesians in structure.',
  '1TH': '1 Thessalonians encourages a young, persecuted church and answers questions about Christ’s return and those who have died before it. It’s one of Paul’s earliest and warmest letters.',
  '2TH': '2 Thessalonians corrects confusion about the day of the Lord, calming fears that it had already happened and calling the church to steady, working patience. It complements the first letter’s themes.',
  '1TI': '1 Timothy is Paul’s pastoral guidance to a young leader on church order, qualifications for overseers and deacons, and guarding sound doctrine. It’s practical instruction for shepherding a church.',
  '2TI': '2 Timothy is Paul’s final letter, written awaiting execution, urging Timothy to guard the gospel and "fight the good fight." "All Scripture is God-breathed" comes from here.',
  TIT: 'Titus instructs a co-worker organizing churches on Crete, emphasizing sound teaching paired with good works. It stresses that grace trains believers toward godly living, not license.',
  PHM: 'Philemon is Paul’s brief, personal appeal on behalf of Onesimus, a runaway slave now a believer, asking Philemon to receive him "no longer as a slave, but... as a dear brother." It’s theology worked out in one relationship.',
  HEB: 'Hebrews argues that Jesus is superior to every Old Testament mediator — angels, Moses, the priesthood — as the final high priest and once-for-all sacrifice. It urges readers not to drift back from Christ.',
  JAS: 'James is intensely practical, insisting that genuine faith always produces visible works — in speech, in caring for the poor, in patience under trial. "Faith without works is dead" is its best-known line.',
  '1PE': '1 Peter encourages Christians facing suffering and social hostility to live honorably as "exiles" whose hope rests in Christ’s resurrection. It models how to suffer well without losing hope.',
  '2PE': '2 Peter warns against false teachers and scoffers who deny Christ’s return, urging growth in faith and holding firmly to apostolic testimony. It closes looking forward to "a new heaven and a new earth."',
  '1JN': '1 John reassures believers of their salvation, testing true faith by love for others, obedience, and belief in Christ come in the flesh. "God is love" is one of its central declarations.',
  '2JN': '2 John is a brief letter warning a church ("the elect lady") to reject traveling false teachers while continuing to walk in love. It’s a snapshot of hospitality and discernment held together.',
  '3JN': '3 John commends Gaius for hospitality to traveling missionaries and confronts Diotrephes, a leader who refused it. It’s the New Testament’s shortest book, about a very concrete church dispute.',
  JUD: 'Jude urgently warns against false teachers who had infiltrated the church, drawing on vivid Old Testament examples of judgment. It closes with one of the Bible’s most quoted benedictions.',
  REV: 'Revelation unveils, through vivid apocalyptic imagery, Christ’s ultimate victory over evil and the renewal of all creation. Written to encourage persecuted churches, it ends with God dwelling with his people forever.',
};
