// GENERATED by scripts/build-scene-narration.js — do not edit by hand.
//
// Which pre-recorded line belongs to which vantage, event, pin or barrier of
// which scene. The tour and every panel's read-aloud button play these straight
// off the origin; the fish-tts round-trip in src/lib/sceneNarration.js is only
// the fallback for a line that is missing here (one edited since the last
// build, most likely).
//
// Filenames carry a hash of the voice and the exact text, so a stale recording
// can never be served under an edited blurb: the lookup simply misses and the
// runtime path takes over until someone re-runs the script.

// The voice these were recorded in. Used to pick the nearest match when the
// runtime fallback does have to synthesise, so the tour does not change voice
// halfway through.
export const NARRATION_VOICE = 'Rico';

export const SCENE_NARRATION = {
  'second-temple': {
    'solomons-portico': { file: '/assets/scenes/second-temple/narration/solomons-portico-762aa681.mp3', chars: 242 },
    'the-soreg': { file: '/assets/scenes/second-temple/narration/the-soreg-9f75b99d.mp3', chars: 302 },
    'court-of-women': { file: '/assets/scenes/second-temple/narration/court-of-women-d5bcb9af.mp3', chars: 290 },
    'fifteen-steps': { file: '/assets/scenes/second-temple/narration/fifteen-steps-46b2f43f.mp3', chars: 240 },
    'before-the-altar': { file: '/assets/scenes/second-temple/narration/before-the-altar-a2ca0bb5.mp3', chars: 331 },
    'hotspot:sanctuary': { file: '/assets/scenes/second-temple/narration/hotspot-sanctuary-a22d451e.mp3', chars: 325 },
    'hotspot:altar': { file: '/assets/scenes/second-temple/narration/hotspot-altar-24fc93ba.mp3', chars: 230 },
    'hotspot:nicanor-gate': { file: '/assets/scenes/second-temple/narration/hotspot-nicanor-gate-fa9ed3ce.mp3', chars: 238 },
    'hotspot:treasury': { file: '/assets/scenes/second-temple/narration/hotspot-treasury-e175b7cc.mp3', chars: 223 },
    'hotspot:soreg': { file: '/assets/scenes/second-temple/narration/hotspot-soreg-e41eec9e.mp3', chars: 262 },
    'hotspot:portico': { file: '/assets/scenes/second-temple/narration/hotspot-portico-6c7fee63.mp3', chars: 258 },
    'hotspot:olivet': { file: '/assets/scenes/second-temple/narration/hotspot-olivet-a4996ac4.mp3', chars: 240 },
    'barrier:soreg': { file: '/assets/scenes/second-temple/narration/barrier-soreg-3713e2da.mp3', chars: 413 },
    'barrier:rail': { file: '/assets/scenes/second-temple/narration/barrier-rail-12e069da.mp3', chars: 280 },
    'barrier:sanctuary': { file: '/assets/scenes/second-temple/narration/barrier-sanctuary-7f05acd1.mp3', chars: 278 },
  },
  'caesarea': {
    'waterfront': { file: '/assets/scenes/caesarea/narration/waterfront-9928787f.mp3', chars: 173 },
    'harbor-view': { file: '/assets/scenes/caesarea/narration/harbor-view-3482ab8c.mp3', chars: 142 },
    'palace-view': { file: '/assets/scenes/caesarea/narration/palace-view-550e2488.mp3', chars: 186 },
    'household-view': { file: '/assets/scenes/caesarea/narration/household-view-2f8cd1e2.mp3', chars: 176 },
    'departure-view': { file: '/assets/scenes/caesarea/narration/departure-view-4a86f785.mp3', chars: 196 },
    'hotspot:sebastos': { file: '/assets/scenes/caesarea/narration/hotspot-sebastos-3472a8f6.mp3', chars: 200 },
    'hotspot:praetorium': { file: '/assets/scenes/caesarea/narration/hotspot-praetorium-c3b44391.mp3', chars: 210 },
    'hotspot:testimony': { file: '/assets/scenes/caesarea/narration/hotspot-testimony-3006759b.mp3', chars: 197 },
    'hotspot:cornelius': { file: '/assets/scenes/caesarea/narration/hotspot-cornelius-c1ab22b2.mp3', chars: 210 },
    'hotspot:philip': { file: '/assets/scenes/caesarea/narration/hotspot-philip-1b105f10.mp3', chars: 235 },
    'hotspot:departure': { file: '/assets/scenes/caesarea/narration/hotspot-departure-8145f747.mp3', chars: 210 },
    'barrier:waterfront-edge': { file: '/assets/scenes/caesarea/narration/barrier-waterfront-edge-fb9db338.mp3', chars: 167 },
    'barrier:palace-boundary': { file: '/assets/scenes/caesarea/narration/barrier-palace-boundary-50a5b53f.mp3', chars: 158 },
  },
  'capernaum': {
    'the-shore': { file: '/assets/scenes/capernaum/narration/the-shore-c3506707.mp3', chars: 274 },
    'the-tax-booth': { file: '/assets/scenes/capernaum/narration/the-tax-booth-6ccbcdd2.mp3', chars: 513 },
    'the-doorway': { file: '/assets/scenes/capernaum/narration/the-doorway-f8046133.mp3', chars: 453 },
    'inside-the-house': { file: '/assets/scenes/capernaum/narration/inside-the-house-9121c850.mp3', chars: 331 },
    'on-the-roof': { file: '/assets/scenes/capernaum/narration/on-the-roof-a3581dcc.mp3', chars: 287 },
    'the-synagogue': { file: '/assets/scenes/capernaum/narration/the-synagogue-cac95b82.mp3', chars: 292 },
    'event:fishermen': { file: '/assets/scenes/capernaum/narration/event-fishermen-3135d9fe.mp3', chars: 536 },
    'event:synagogue-rebuke': { file: '/assets/scenes/capernaum/narration/event-synagogue-rebuke-29f96563.mp3', chars: 448 },
    'event:mother-in-law': { file: '/assets/scenes/capernaum/narration/event-mother-in-law-da879358.mp3', chars: 403 },
    'event:sundown': { file: '/assets/scenes/capernaum/narration/event-sundown-43b55bb8.mp3', chars: 450 },
    'event:paralytic': { file: '/assets/scenes/capernaum/narration/event-paralytic-68e681f7.mp3', chars: 515 },
    'event:call-of-matthew': { file: '/assets/scenes/capernaum/narration/event-call-of-matthew-05f00f9d.mp3', chars: 389 },
    'event:centurion': { file: '/assets/scenes/capernaum/narration/event-centurion-8d62f87c.mp3', chars: 582 },
    'event:the-woman': { file: '/assets/scenes/capernaum/narration/event-the-woman-8dd40402.mp3', chars: 591 },
    'event:bread-of-life': { file: '/assets/scenes/capernaum/narration/event-bread-of-life-c6ec802e.mp3', chars: 621 },
    'event:temple-tax': { file: '/assets/scenes/capernaum/narration/event-temple-tax-cfdbb406.mp3', chars: 488 },
    'event:the-child': { file: '/assets/scenes/capernaum/narration/event-the-child-776f9128.mp3', chars: 452 },
    'hotspot:the-lake': { file: '/assets/scenes/capernaum/narration/hotspot-the-lake-9937a382.mp3', chars: 296 },
    'hotspot:the-boats': { file: '/assets/scenes/capernaum/narration/hotspot-the-boats-9967668f.mp3', chars: 309 },
    'hotspot:the-house': { file: '/assets/scenes/capernaum/narration/hotspot-the-house-4d1b0081.mp3', chars: 517 },
    'hotspot:the-lowered-man': { file: '/assets/scenes/capernaum/narration/hotspot-the-lowered-man-2a19c49e.mp3', chars: 317 },
    'hotspot:the-roof': { file: '/assets/scenes/capernaum/narration/hotspot-the-roof-239a1fe7.mp3', chars: 396 },
    'hotspot:the-basalt-synagogue': { file: '/assets/scenes/capernaum/narration/hotspot-the-basalt-synagogue-161278dc.mp3', chars: 470 },
    'hotspot:the-unclean-spirit': { file: '/assets/scenes/capernaum/narration/hotspot-the-unclean-spirit-3cfec063.mp3', chars: 802 },
    'hotspot:the-reading': { file: '/assets/scenes/capernaum/narration/hotspot-the-reading-833db531.mp3', chars: 591 },
    'hotspot:the-cast-net': { file: '/assets/scenes/capernaum/narration/hotspot-the-cast-net-b97927e9.mp3', chars: 508 },
    'hotspot:she-served-them': { file: '/assets/scenes/capernaum/narration/hotspot-she-served-them-b336b96d.mp3', chars: 297 },
    'hotspot:after-sunset': { file: '/assets/scenes/capernaum/narration/hotspot-after-sunset-57ae2561.mp3', chars: 449 },
    'hotspot:under-my-roof': { file: '/assets/scenes/capernaum/narration/hotspot-under-my-roof-3abad1f6.mp3', chars: 439 },
    'hotspot:the-fringe': { file: '/assets/scenes/capernaum/narration/hotspot-the-fringe-d9e6ebb7.mp3', chars: 438 },
    'hotspot:a-hard-saying': { file: '/assets/scenes/capernaum/narration/hotspot-a-hard-saying-a82e648a.mp3', chars: 390 },
    'hotspot:a-shekel': { file: '/assets/scenes/capernaum/narration/hotspot-a-shekel-f191d92b.mp3', chars: 384 },
    'hotspot:last-of-all': { file: '/assets/scenes/capernaum/narration/hotspot-last-of-all-5ecb5f73.mp3', chars: 333 },
    'hotspot:the-call-of-matthew': { file: '/assets/scenes/capernaum/narration/hotspot-the-call-of-matthew-df1c0fee.mp3', chars: 605 },
    'hotspot:the-tax-road': { file: '/assets/scenes/capernaum/narration/hotspot-the-tax-road-b3035d24.mp3', chars: 409 },
    'hotspot:the-harbour': { file: '/assets/scenes/capernaum/narration/hotspot-the-harbour-a3662121.mp3', chars: 529 },
    'hotspot:the-fold': { file: '/assets/scenes/capernaum/narration/hotspot-the-fold-18445993.mp3', chars: 325 },
    'hotspot:the-harvest': { file: '/assets/scenes/capernaum/narration/hotspot-the-harvest-27b363c9.mp3', chars: 352 },
    'hotspot:arbel': { file: '/assets/scenes/capernaum/narration/hotspot-arbel-ef2ed002.mp3', chars: 442 },
    'hotspot:the-far-shore': { file: '/assets/scenes/capernaum/narration/hotspot-the-far-shore-6f718c97.mp3', chars: 469 },
    'hotspot:the-woe': { file: '/assets/scenes/capernaum/narration/hotspot-the-woe-824ca550.mp3', chars: 401 },
    'barrier:water': { file: '/assets/scenes/capernaum/narration/barrier-water-f9cd7987.mp3', chars: 238 },
    'barrier:roof-opening': { file: '/assets/scenes/capernaum/narration/barrier-roof-opening-6fe14231.mp3', chars: 353 },
    'barrier:door-crowd': { file: '/assets/scenes/capernaum/narration/barrier-door-crowd-dcca554b.mp3', chars: 368 },
    'barrier:parapet': { file: '/assets/scenes/capernaum/narration/barrier-parapet-dcde3385.mp3', chars: 493 },
    'barrier:village-edge': { file: '/assets/scenes/capernaum/narration/barrier-village-edge-a9ac544b.mp3', chars: 335 },
  },
  'tabernacle': {
    'the-camp': { file: '/assets/scenes/tabernacle/narration/the-camp-b8612282.mp3', chars: 322 },
    'camp-life': { file: '/assets/scenes/tabernacle/narration/camp-life-f0be9f35.mp3', chars: 197 },
    'the-gate': { file: '/assets/scenes/tabernacle/narration/the-gate-d8a132e0.mp3', chars: 309 },
    'the-altar': { file: '/assets/scenes/tabernacle/narration/the-altar-c9a7d95c.mp3', chars: 286 },
    'the-laver': { file: '/assets/scenes/tabernacle/narration/the-laver-1b5dacea.mp3', chars: 269 },
    'the-high-priest': { file: '/assets/scenes/tabernacle/narration/the-high-priest-5bb46884.mp3', chars: 320 },
    'the-holy-place': { file: '/assets/scenes/tabernacle/narration/the-holy-place-9169bc22.mp3', chars: 244 },
    'before-the-veil': { file: '/assets/scenes/tabernacle/narration/before-the-veil-500b0ad6.mp3', chars: 582 },
    'hotspot:high-priest-vestments': { file: '/assets/scenes/tabernacle/narration/hotspot-high-priest-vestments-a98e6ef0.mp3', chars: 344 },
    'hotspot:levite-attendants': { file: '/assets/scenes/tabernacle/narration/hotspot-levite-attendants-f9ce7838.mp3', chars: 261 },
    'hotspot:the-cloud': { file: '/assets/scenes/tabernacle/narration/hotspot-the-cloud-623d5afa.mp3', chars: 300 },
    'hotspot:the-gate-screen': { file: '/assets/scenes/tabernacle/narration/hotspot-the-gate-screen-e29e0a6c.mp3', chars: 288 },
    'hotspot:the-boards': { file: '/assets/scenes/tabernacle/narration/hotspot-the-boards-a6c2f350.mp3', chars: 320 },
    'hotspot:the-coverings': { file: '/assets/scenes/tabernacle/narration/hotspot-the-coverings-d1799164.mp3', chars: 356 },
    'hotspot:the-bronze-altar': { file: '/assets/scenes/tabernacle/narration/hotspot-the-bronze-altar-830f89b8.mp3', chars: 235 },
    'hotspot:the-laver-basin': { file: '/assets/scenes/tabernacle/narration/hotspot-the-laver-basin-cca83924.mp3', chars: 296 },
    'hotspot:the-lampstand': { file: '/assets/scenes/tabernacle/narration/hotspot-the-lampstand-2038d064.mp3', chars: 308 },
    'hotspot:the-table': { file: '/assets/scenes/tabernacle/narration/hotspot-the-table-95276e14.mp3', chars: 308 },
    'hotspot:the-incense-altar': { file: '/assets/scenes/tabernacle/narration/hotspot-the-incense-altar-6cabf9aa.mp3', chars: 333 },
    'hotspot:the-ark': { file: '/assets/scenes/tabernacle/narration/hotspot-the-ark-b35a5b99.mp3', chars: 351 },
    'hotspot:the-camp-of-israel': { file: '/assets/scenes/tabernacle/narration/hotspot-the-camp-of-israel-f509ac5e.mp3', chars: 302 },
    'barrier:veil': { file: '/assets/scenes/tabernacle/narration/barrier-veil-4f52c19a.mp3', chars: 409 },
    'barrier:court-hanging': { file: '/assets/scenes/tabernacle/narration/barrier-court-hanging-22c7011d.mp3', chars: 264 },
    'barrier:desert': { file: '/assets/scenes/tabernacle/narration/barrier-desert-7ae62dd2.mp3', chars: 309 },
  },
  'valley-of-elah': {
    'reference-view': { file: '/assets/scenes/valley-of-elah/narration/reference-view-e9049c42.mp3', chars: 258 },
    'beside-david': { file: '/assets/scenes/valley-of-elah/narration/beside-david-76580767.mp3', chars: 169 },
    'facing-goliath': { file: '/assets/scenes/valley-of-elah/narration/facing-goliath-40a04faf.mp3', chars: 257 },
    'valley-overview': { file: '/assets/scenes/valley-of-elah/narration/valley-overview-5e07bc23.mp3', chars: 232 },
    'hotspot:david': { file: '/assets/scenes/valley-of-elah/narration/hotspot-david-25009e18.mp3', chars: 267 },
    'hotspot:goliath': { file: '/assets/scenes/valley-of-elah/narration/hotspot-goliath-065f9783.mp3', chars: 235 },
    'hotspot:shield-bearer': { file: '/assets/scenes/valley-of-elah/narration/hotspot-shield-bearer-36a1cc4f.mp3', chars: 195 },
    'hotspot:philistine-ranks': { file: '/assets/scenes/valley-of-elah/narration/hotspot-philistine-ranks-0f6a60af.mp3', chars: 181 },
    'hotspot:israelite-ranks': { file: '/assets/scenes/valley-of-elah/narration/hotspot-israelite-ranks-e294820e.mp3', chars: 157 },
    'hotspot:the-brook': { file: '/assets/scenes/valley-of-elah/narration/hotspot-the-brook-a943520d.mp3', chars: 195 },
    'hotspot:valley-corridor': { file: '/assets/scenes/valley-of-elah/narration/hotspot-valley-corridor-6e2bcddb.mp3', chars: 189 },
    'barrier:valley-bounds': { file: '/assets/scenes/valley-of-elah/narration/barrier-valley-bounds-062ed83a.mp3', chars: 149 },
    'barrier:goliath-perimeter': { file: '/assets/scenes/valley-of-elah/narration/barrier-goliath-perimeter-49a82827.mp3', chars: 129 },
    'barrier:david-perimeter': { file: '/assets/scenes/valley-of-elah/narration/barrier-david-perimeter-57c7f621.mp3', chars: 88 },
    'barrier:steep-slope': { file: '/assets/scenes/valley-of-elah/narration/barrier-steep-slope-6f2fc1cc.mp3', chars: 89 },
  },
};

// The recorded line for one vantage (or, with `kind`, one event, hotspot or
// barrier), or null if there isn't one.
export function narrationFor(slug, id, kind = 'vantage') {
  return SCENE_NARRATION[slug]?.[kind === 'vantage' ? id : `${kind}:${id}`] || null;
}
