// GENERATED by scripts/build-scene-narration.js — do not edit by hand.
//
// Which pre-recorded line belongs to which vantage of which scene. The tour
// plays these straight off the origin; the fish-tts round-trip in
// src/lib/sceneNarration.js is only the fallback for a stop that is missing
// here (a blurb edited since the last build, most likely).
//
// Filenames carry a hash of the voice and the exact text, so a stale recording
// can never be served under an edited blurb: the lookup simply misses and the
// runtime path takes over until someone re-runs the script.

// The voice these were recorded in. Used to pick the nearest match when the
// runtime fallback does have to synthesise, so the tour does not change voice
// halfway through.
export const NARRATION_VOICE = 'Rico';

export const SCENE_NARRATION = {
  'second-temple': {
    'solomons-portico': { file: '/assets/scenes/second-temple/narration/solomons-portico-762aa681.mp3', chars: 242 },
    'the-soreg': { file: '/assets/scenes/second-temple/narration/the-soreg-9f75b99d.mp3', chars: 302 },
    'court-of-women': { file: '/assets/scenes/second-temple/narration/court-of-women-d5bcb9af.mp3', chars: 290 },
    'fifteen-steps': { file: '/assets/scenes/second-temple/narration/fifteen-steps-46b2f43f.mp3', chars: 240 },
    'before-the-altar': { file: '/assets/scenes/second-temple/narration/before-the-altar-a2ca0bb5.mp3', chars: 331 },
  },
  'caesarea': {
    'waterfront': { file: '/assets/scenes/caesarea/narration/waterfront-9928787f.mp3', chars: 173 },
    'harbor-view': { file: '/assets/scenes/caesarea/narration/harbor-view-3482ab8c.mp3', chars: 142 },
    'palace-view': { file: '/assets/scenes/caesarea/narration/palace-view-550e2488.mp3', chars: 186 },
    'household-view': { file: '/assets/scenes/caesarea/narration/household-view-2f8cd1e2.mp3', chars: 176 },
    'departure-view': { file: '/assets/scenes/caesarea/narration/departure-view-4a86f785.mp3', chars: 196 },
  },
  'capernaum': {
    'the-shore': { file: '/assets/scenes/capernaum/narration/the-shore-c3506707.mp3', chars: 274 },
    'the-tax-booth': { file: '/assets/scenes/capernaum/narration/the-tax-booth-6ccbcdd2.mp3', chars: 513 },
    'the-doorway': { file: '/assets/scenes/capernaum/narration/the-doorway-f8046133.mp3', chars: 453 },
    'inside-the-house': { file: '/assets/scenes/capernaum/narration/inside-the-house-9121c850.mp3', chars: 331 },
    'on-the-roof': { file: '/assets/scenes/capernaum/narration/on-the-roof-a3581dcc.mp3', chars: 287 },
    'the-synagogue': { file: '/assets/scenes/capernaum/narration/the-synagogue-cac95b82.mp3', chars: 292 },
  },
  'tabernacle': {
    'the-camp': { file: '/assets/scenes/tabernacle/narration/the-camp-b8612282.mp3', chars: 322 },
    'the-gate': { file: '/assets/scenes/tabernacle/narration/the-gate-d8a132e0.mp3', chars: 309 },
    'the-altar': { file: '/assets/scenes/tabernacle/narration/the-altar-c9a7d95c.mp3', chars: 286 },
    'the-laver': { file: '/assets/scenes/tabernacle/narration/the-laver-1b5dacea.mp3', chars: 269 },
    'the-holy-place': { file: '/assets/scenes/tabernacle/narration/the-holy-place-9169bc22.mp3', chars: 244 },
    'before-the-veil': { file: '/assets/scenes/tabernacle/narration/before-the-veil-134faffb.mp3', chars: 297 },
  },
};

// The recorded line for one vantage, or null if there isn't one.
export function narrationFor(slug, vantageId) {
  return SCENE_NARRATION[slug]?.[vantageId] || null;
}
