import { groundAt, SITES } from '../components/scene/sinaiDimensions';

const eye = (x, z) => [x, groundAt(x, z) + 1.7, z];
const at = (x, z, h = 1.2) => [x, groundAt(x, z) + h, z];
const stop = (id, label, site, blurb, refs, event, distance = 9) => {
  const { x, z } = SITES[site];
  return { id, label, position: eye(x, z + distance), lookAt: at(x, z), blurb, refs, event };
};
const event = (id, label, era, site, hour, body, refs, distance = 9) => {
  const { x, z } = SITES[site];
  return {
    id,
    label,
    era,
    site,
    place: SITE_LABELS[site],
    hour,
    position: eye(x, z + distance),
    lookAt: at(x, z),
    body,
    refs,
  };
};
const SITE_LABELS = {
  bush: 'The shepherd’s wilderness',
  water: 'The rock at Horeb',
  camp: 'The gathering place',
  altar: 'At the foot of the mountain',
  elders: 'The mountain terrace',
  summit: 'The upper mountain',
  cleft: 'A cleft in the rock',
  cave: 'The cave on Horeb',
  tent: 'Outside the camp',
  sanctuary: 'The sanctuary court',
  workshop: 'The craftsmen’s camp',
  calf: 'The camp below',
  departure: 'The wilderness road',
};
const CALL = 'Moses’ calling',
  CAMP = 'Israel at the mountain',
  COVENANT = 'Covenant and renewal';
const WORSHIP = 'The sanctuary and the journey',
  ELIJAH = 'Elijah at Horeb';

export const SINAI = {
  slug: 'sinai',
  placeSlug: 'sinai',
  title: 'Mount Sinai / Horeb',
  subtitle: 'Mountain of God · Moses to Elijah',
  period: { label: 'Moses to Elijah · multiple periods', referenceYear: null },
  geo: { lat: 28.5397, lon: 33.9733, bearing: 0, xAxis: 90 },
  defaultVantage: 'mountain-foot',
  defaultEvent: 'revelation',
  defaultTimeOfDay: 'morning',
  eventsHeading: 'From Moses’ calling to Elijah’s commission',
  blurb:
    'Follow the biblical story of Sinai and Horeb: the burning bush, the covenant, the wilderness sanctuary, and Elijah’s encounter centuries later. Walk the mountain paths in first or third person, choose a moment in the story, and explore how later Scripture remembers this mountain.',
  disclaimer:
    'An interpretive landscape, not a surveyed reconstruction. Sinai and Horeb are traditionally identified with the same mountain or mountain region; the modern location is disputed. The Atlas point follows the traditional southern Sinai identification. Settings and distances are compressed for exploration. The camp is representative, not a count of Israel; the figures, cave, terrain and weather are artistic interpretations. God is not represented by a human figure. Later biblical recollections are reading stops, not additional visits staged here. Episode order follows the narrative broadly; Numbers also recounts earlier events.',
  vantages: [
    stop(
      'mountain-foot',
      'Before the Mountain',
      'altar',
      'Israel camps before the mountain. Exodus describes boundaries, thunder, cloud, fire and a trembling people. This open approach leads from their tents to the mountain paths; its distances and layout are interpretive.',
      ['Exodus 19:1-25', 'Deuteronomy 5:1-5'],
      'revelation',
      14,
    ),
    stop(
      'holy-ground',
      'Holy Ground',
      'bush',
      'Before leading Israel here, Moses tends Jethro’s flock near Horeb. A bush burns without being consumed. The call begins with a command to remove his sandals, and sends him back toward Egypt.',
      ['Exodus 3:1-12'],
      'burning-bush',
    ),
    stop(
      'rock-water',
      'Water at Horeb',
      'water',
      'Exodus places the thirsty people at Rephidim and names the rock at Horeb. Moses takes the elders with him. This stop brings that episode into the walk without claiming that its location lay a few steps from the later camp.',
      ['Exodus 17:1-7'],
      'water-rock',
      10,
    ),
    stop(
      'israel-camp',
      'Among the Tents',
      'camp',
      'At Sinai, the people hear the covenant, learn how to live and worship, and prepare to journey onward. Choose an episode to move between the assembly, the craftsmen, and the ordered camp.',
      ['Exodus 19:1-8', 'Numbers 1:1-4', 'Numbers 10:11-13'],
      'arrival',
    ),
    stop(
      'covenant-table',
      'The Covenant Meal',
      'elders',
      'Moses, Aaron, Nadab, Abihu and seventy elders ascend. Exodus describes a vision of God with something like sapphire pavement under his feet, and says they eat and drink. The meal is represented here without attempting a bodily depiction of God.',
      ['Exodus 24:9-11'],
      'elders-meal',
    ),
    stop(
      'upper-mountain',
      'The Upper Mountain',
      'summit',
      'Moses enters the cloud and remains on the mountain forty days and nights. Here the story turns to the tablets and the instructions for the sanctuary. The arrangement of the summit and approach is imagined.',
      ['Exodus 24:12-18', 'Exodus 31:18'],
      'tablets',
    ),
    stop(
      'rock-cleft',
      'The Cleft in the Rock',
      'cleft',
      'After the broken covenant, Moses asks to know God’s ways and see his glory. Exodus describes shelter in a cleft as God passes by. Light against the rock suggests the encounter without claiming to show God’s appearance.',
      ['Exodus 33:12-23', 'Exodus 34:5-7'],
      'cleft-glory',
    ),
    stop(
      'wilderness-sanctuary',
      'The Wilderness Sanctuary',
      'sanctuary',
      'The Tabernacle belongs to a later stage of the camp’s story. Exodus ends with its completion and the cloud filling it. This outdoor view represents its place in the Sinai narrative; the separate Tabernacle environment offers a closer architectural exploration.',
      ['Exodus 40:1-38', 'Leviticus 1:1'],
      'tabernacle-raised',
      19,
    ),
    stop(
      'elijah-cave',
      'Elijah’s Cave',
      'cave',
      'Centuries after Moses, Elijah reaches Horeb after forty days and nights. He lodges in a cave and hears the question, What are you doing here, Elijah? Scripture does not identify this cave with Moses’ cleft.',
      ['1 Kings 19:8-18'],
      'elijah-cave',
      9,
    ),
    stop(
      'journey-road',
      'The Cloud Goes Before Them',
      'departure',
      'In the second year, the cloud lifts and Israel leaves the wilderness of Sinai in ordered divisions. The route beyond this small landscape is not reconstructed. The journey continues toward the wilderness of Paran.',
      ['Numbers 9:15-23', 'Numbers 10:11-36'],
      'departure',
      10,
    ),
  ],
  events: [
    event(
      'burning-bush',
      'A Bush That Is Not Consumed',
      CALL,
      'bush',
      'dawn',
      'Moses leads Jethro’s flock to Horeb, the mountain of God. The angel of the Lord appears in a flame within a bush that is not consumed. God calls Moses by name, tells him to remove his sandals, and commissions him to bring Israel out of Egypt. The living branches and flame evoke the sign; the place and appearance of the bush are not known.',
      ['Exodus 3:1-22'],
    ),
    event(
      'signs',
      'The Staff Becomes a Serpent',
      CALL,
      'bush',
      'morning',
      'Moses asks how the people will believe him. His staff becomes a serpent, then a staff again; his hand is afflicted and restored. God also instructs him about a future sign with Nile water. Aaron will speak alongside him. The serpent shown here represents the first sign; the Nile-water sign belongs in Egypt, not on this mountain.',
      ['Exodus 4:1-17'],
    ),
    event(
      'aaron-meets-moses',
      'Brothers Meet at the Mountain',
      CALL,
      'bush',
      'noon',
      'The Lord sends Aaron into the wilderness to meet Moses. They meet at the mountain of God, and Aaron kisses him. Moses tells Aaron the words of his commission and the signs. Their subsequent meeting with Israel’s elders takes place in Egypt, beyond this environment.',
      ['Exodus 4:27-31'],
    ),
    event(
      'water-rock',
      'Water from the Rock',
      CAMP,
      'water',
      'noon',
      'At Rephidim, the people quarrel with Moses because they have no water. God sends Moses ahead with elders and the staff, to the rock at Horeb. Moses strikes it and water comes out. The place is called Massah and Meribah. This is the Exodus episode, distinct from the later incident at Kadesh in Numbers 20.',
      ['Exodus 17:1-7'],
    ),
    event(
      'jethro',
      'Jethro Visits and Gives Counsel',
      CAMP,
      'camp',
      'morning',
      'Jethro brings Zipporah and Moses’ sons to the camp at the mountain of God. He rejoices at Israel’s deliverance and shares a meal with Aaron and the elders. Seeing Moses hear disputes all day, he advises appointing trustworthy leaders for the smaller matters. The gathered listeners represent that counsel, not a complete assembly.',
      ['Exodus 18:1-27'],
    ),
    event(
      'arrival',
      'Israel Camps Before Sinai',
      CAMP,
      'camp',
      'morning',
      'In the third month after leaving Egypt, Israel enters the wilderness of Sinai and camps before the mountain. Moses goes up to hear God’s covenant invitation, then brings the words to the elders and people. The tents suggest a much larger encampment whose precise layout is not described here.',
      ['Exodus 19:1-8'],
    ),
    event(
      'preparation',
      'Prepare for the Third Day',
      CAMP,
      'altar',
      'noon',
      'Moses consecrates the people, who wash their garments and prepare for the third day. Boundaries are set around the mountain, and the people are warned not to cross them. The stone markers shown suggest the boundary without claiming that Scripture specifies their material or form.',
      ['Exodus 19:9-15'],
    ),
    event(
      'revelation',
      'Cloud, Fire and the Trumpet',
      CAMP,
      'altar',
      'morning',
      'On the third morning there are thunder, lightning, a thick cloud and a very loud trumpet. Moses brings the people to the foot of the mountain. Sinai is wrapped in smoke because the Lord descends upon it in fire, and the mountain trembles. Cloud and a steady fire glow suggest this encounter without flashing effects or a bodily depiction of God.',
      ['Exodus 19:16-25'],
      14,
    ),
    event(
      'commandments',
      'The Ten Commandments',
      CAMP,
      'altar',
      'morning',
      'God speaks the commandments to Israel. The people see the thunder and lightning, hear the trumpet, and stand at a distance in fear. They ask Moses to speak with them. Moses draws near to the thick darkness where God is, and further instructions follow. The tablets are not yet being presented to the camp in this moment.',
      ['Exodus 20:1-26', 'Exodus 21:1-23:33'],
      14,
    ),
    event(
      'covenant',
      'An Altar and Twelve Pillars',
      COVENANT,
      'altar',
      'dawn',
      'Moses writes the Lord’s words, builds an altar at the foot of the mountain and sets up twelve pillars for Israel’s twelve tribes. Young men offer sacrifices. Moses reads the book of the covenant, and the people promise obedience. He applies the blood of the covenant. The altar, pillars and scroll represent the ceremony without graphic sacrifice.',
      ['Exodus 24:1-8'],
    ),
    event(
      'elders-meal',
      'They Saw, and Ate and Drank',
      COVENANT,
      'elders',
      'noon',
      'Moses, Aaron, Nadab, Abihu and seventy elders ascend. Exodus describes a vision with something like sapphire pavement, clear as the sky, beneath God’s feet. The leaders eat and drink. A small representative group, a meal and a blue-lit stone surface recall the passage; no human figure attempts to represent God.',
      ['Exodus 24:9-11'],
    ),
    event(
      'tablets',
      'Forty Days in the Cloud',
      COVENANT,
      'summit',
      'morning',
      'Moses goes up with Joshua his assistant, leaving the elders with Aaron and Hur. The cloud covers the mountain; on the seventh day God calls Moses into it. Moses remains forty days and nights, receiving instructions for the sanctuary and priesthood, and two stone tablets written by the finger of God. Joshua is shown lower on the approach.',
      ['Exodus 24:12-18', 'Exodus 25:1-31:18'],
    ),
    event(
      'golden-calf',
      'The Golden Calf',
      COVENANT,
      'calf',
      'noon',
      'While Moses delays, the people ask Aaron for gods to go before them. Aaron receives gold earrings and makes a molten calf; an altar and feast follow. The calf scene appears only in this episode. Its exact shape is unknown. The story presents the act as a grave breach of the covenant, not as approved worship.',
      ['Exodus 32:1-6'],
    ),
    event(
      'broken-tablets',
      'The Tablets Are Broken',
      COVENANT,
      'calf',
      'noon',
      'Moses descends with the tablets and meets Joshua. When he sees the calf and the dancing, he breaks the tablets at the foot of the mountain. He destroys the calf and confronts Aaron. The chapter also recounts the Levites’ killing of about three thousand people; the broken stones and subdued gathering evoke the crisis without depicting the violence.',
      ['Exodus 32:15-29'],
    ),
    event(
      'intercession',
      'Moses Pleads for the People',
      COVENANT,
      'summit',
      'dusk',
      'Moses intercedes when God first announces judgment, appealing to the promises to Abraham, Isaac and Israel. After the calf is destroyed, Moses returns to seek forgiveness, even offering to be blotted from God’s book. Judgment and the question of God’s presence remain before the people. This scene brings together the two prayers identified in Exodus 32.',
      ['Exodus 32:7-14', 'Exodus 32:30-35', 'Exodus 33:1-6'],
    ),
    event(
      'meeting-tent',
      'The Tent Outside the Camp',
      COVENANT,
      'tent',
      'morning',
      'Moses pitches a tent of meeting outside the camp. When he enters, a pillar of cloud stands at its entrance, and the people worship at their own tent doors. The Lord speaks with Moses as a man speaks with his friend; Joshua remains at the tent. This is distinguished from the sanctuary constructed later in Exodus.',
      ['Exodus 33:7-11'],
      -9,
    ),
    event(
      'cleft-glory',
      'Show Me Your Glory',
      COVENANT,
      'cleft',
      'dawn',
      'Moses asks for God’s presence to go with the people, then asks to see his glory. God promises to make his goodness pass before Moses and proclaim his name. Moses is sheltered in a cleft of the rock. A warm light over the stone suggests the encounter; the scene does not attempt to portray God’s face or body.',
      ['Exodus 33:12-23'],
    ),
    event(
      'renewal',
      'New Tablets and a Renewed Covenant',
      COVENANT,
      'summit',
      'dawn',
      'Moses cuts two new stone tablets and returns alone to the mountain. The Lord proclaims his name and character: merciful and gracious, yet not treating guilt as nothing. Moses bows in worship. The covenant is renewed, and Moses remains forty days and nights. The new tablets mark renewal after the broken covenant.',
      ['Exodus 34:1-28', 'Deuteronomy 10:1-5'],
    ),
    event(
      'radiant-face',
      'Moses’ Face Shines',
      COVENANT,
      'camp',
      'noon',
      'Moses comes down with the two tablets, unaware that his face shines from speaking with God. Aaron and the Israelites are afraid to approach. Moses calls them near, gives the commands, and afterward puts a veil over his face. The scene uses a restrained glow; the veil rests nearby before it is worn.',
      ['Exodus 34:29-35'],
    ),
    event(
      'craftsmen',
      'Willing Gifts and Skilled Hands',
      WORSHIP,
      'workshop',
      'morning',
      'The people bring willing offerings of metals, cloth, skins, timber, oil and stones. Bezalel, Oholiab and other skilled workers make the Tabernacle, its furnishings and the priestly garments. So much is given that Moses tells the people to stop bringing gifts. The work tables and woven cloth suggest the making of the sanctuary.',
      ['Exodus 35:1-39:43'],
    ),
    event(
      'tabernacle-raised',
      'The Glory Fills the Tabernacle',
      WORSHIP,
      'sanctuary',
      'morning',
      'On the first day of the first month of the second year, Moses sets up the Tabernacle and arranges its furnishings. A cloud covers the tent of meeting and the Lord’s glory fills it, so Moses cannot enter. The cloud by day and fire by night guide the people’s journeys. This sanctuary now replaces the earlier tent outside the camp in the scene.',
      ['Exodus 40:1-38'],
      19,
    ),
    event(
      'ordination',
      'Aaron and His Sons Are Ordained',
      WORSHIP,
      'sanctuary',
      'morning',
      'At the entrance of the tent of meeting, Moses washes Aaron and his sons, clothes them, anoints the sanctuary and Aaron, and carries out the commanded offerings. They remain at the entrance for seven days. The vested priest and attendants represent this consecration; the sacrificial actions are described rather than shown graphically.',
      ['Leviticus 8:1-36'],
      19,
    ),
    event(
      'first-offerings',
      'The First Offerings and Blessing',
      WORSHIP,
      'sanctuary',
      'noon',
      'On the eighth day, Aaron presents the appointed offerings. He blesses the people; Moses and Aaron enter the tent and come out to bless them together. The Lord’s glory appears, and fire consumes the offering on the altar. The people shout and fall facedown. The altar’s glow recalls this scene without graphic imagery.',
      ['Leviticus 9:1-24'],
      19,
    ),
    event(
      'nadab-abihu',
      'Unauthorized Fire',
      WORSHIP,
      'sanctuary',
      'dusk',
      'Nadab and Abihu offer fire before the Lord that he has not commanded, and fire comes out and they die. Moses speaks of God’s holiness, and Aaron is silent. Their relatives carry them outside the camp. Two unattended censers and a still gathering represent the loss; the scene does not depict bodies or the moment of death.',
      ['Leviticus 10:1-20'],
      19,
    ),
    event(
      'holy-living',
      'Holiness in Worship and Daily Life',
      WORSHIP,
      'camp',
      'morning',
      'From the tent of meeting and at Sinai, the Lord gives Moses instructions about offerings, purity, the Day of Atonement, love of neighbor, holy times, justice and the land’s rest. These are teaching passages rather than one dated assembly. This reading scene includes the difficult camp judgment in Leviticus 24 without staging an execution, and introduces the laws closing Leviticus.',
      [
        'Leviticus 1:1',
        'Leviticus 16:1-34',
        'Leviticus 19:1-37',
        'Leviticus 24:10-23',
        'Leviticus 25:1-27:34',
      ],
    ),
    event(
      'dedication',
      'Gifts for the Sanctuary',
      WORSHIP,
      'sanctuary',
      'morning',
      'Numbers looks back to the dedication of the altar. The tribal leaders bring wagons, oxen and offerings, one leader each day. The Levites are prepared for service, and the lamps are arranged. A representative gift procession recalls these accounts; it does not compress the twelve days into a claim that every gift arrived at once.',
      ['Numbers 7:1-8:26'],
      19,
    ),
    event(
      'passover',
      'Passover in the Wilderness',
      WORSHIP,
      'camp',
      'dusk',
      'In the first month of the second year, Israel keeps Passover in the wilderness of Sinai. Some men, unclean through contact with a dead body, ask Moses how they may take part. God provides for observance in the second month for those prevented by uncleanness or travel. This account precedes the census in time, although Numbers tells it later.',
      ['Numbers 9:1-14'],
    ),
    event(
      'census',
      'Numbered and Arranged by Standards',
      WORSHIP,
      'camp',
      'morning',
      'In the second month of the second year, Moses and Aaron take the commanded census. The tribes camp by their standards around the tent of meeting, with the Levites assigned its care and transport. The standards and small assembly symbolize that order; this compact camp cannot reproduce the numbers or full extent described in Numbers.',
      ['Numbers 1:1-4:49'],
    ),
    event(
      'trumpets',
      'Two Silver Trumpets',
      WORSHIP,
      'departure',
      'morning',
      'The Lord instructs Moses to make two silver trumpets for summoning the assembly and signaling the camps to set out. The cloud determines whether Israel stays or journeys. Moses also invites Hobab to travel with them. Two trumpeters and a waiting company mark the preparation to leave Sinai.',
      ['Numbers 9:15-23', 'Numbers 10:1-10', 'Numbers 10:29-32'],
      10,
    ),
    event(
      'departure',
      'Israel Leaves Sinai',
      WORSHIP,
      'departure',
      'morning',
      'On the twentieth day of the second month of the second year, the cloud lifts. Israel sets out from Sinai in ordered divisions; the Tabernacle is taken down for transport. The ark goes before them as they seek a resting place. The packed loads and departing travelers represent the beginning of the journey toward Paran.',
      ['Numbers 10:11-36'],
      10,
    ),
    event(
      'elijah-cave',
      'Elijah Comes to Horeb',
      ELIJAH,
      'cave',
      'dusk',
      'After fleeing Jezebel and being sustained in the wilderness, Elijah travels forty days and nights to Horeb, the mountain of God. He enters a cave. Asked why he is there, he speaks of his zeal, Israel’s broken covenant, the killing of the prophets, and his fear that he alone is left. Israel’s wilderness camp is now absent.',
      ['1 Kings 19:1-10'],
      9,
    ),
    event(
      'elijah-wind',
      'Wind, Earthquake and Fire',
      ELIJAH,
      'cave',
      'dusk',
      'Elijah is told to stand on the mountain before the Lord. A great wind tears at the mountain and breaks rocks, followed by an earthquake and fire; the passage says the Lord is not in these. Moving dust, scattered stones and a distant fire suggest the sequence, without shaking the visitor’s camera or flashing the screen.',
      ['1 Kings 19:11-12'],
      9,
    ),
    event(
      'elijah-voice',
      'A Quiet Voice and a New Commission',
      ELIJAH,
      'cave',
      'dawn',
      'After the fire comes a still small voice, also translated a gentle whisper or a sound of sheer silence. Elijah wraps his face in his mantle and stands at the cave entrance. God sends him back with a commission concerning Hazael, Jehu and Elisha, and tells him of seven thousand in Israel who have not bowed to Baal. Those later events occur elsewhere.',
      ['1 Kings 19:12-18'],
      9,
    ),
  ],
  hotspots: [
    {
      id: 'sinai-horeb',
      label: 'Sinai and Horeb',
      position: at(6, 9, 4),
      maxDistance: 65,
      body: 'Exodus names Horeb in the burning-bush story and Sinai when Israel camps before the mountain. Deuteronomy repeatedly calls the covenant mountain Horeb. These names are traditionally understood to refer to the same mountain or mountain region. Neither name establishes a universally accepted modern location.',
      refs: ['Exodus 3:1', 'Exodus 19:1-2', 'Deuteronomy 5:2', '1 Kings 19:8'],
    },
    {
      id: 'moses-remembers',
      label: 'Moses Looks Back',
      position: at(4, -55, 3),
      maxDistance: 38,
      body: 'On the plains of Moab, Moses recalls Horeb: the fire, the covenant, the people’s fear, the calf, his intercession and the new tablets. These speeches remember Sinai from another place. They are not additional visits to the mountain.',
      refs: [
        'Deuteronomy 1:6-8',
        'Deuteronomy 4:9-15',
        'Deuteronomy 5:1-33',
        'Deuteronomy 9:7-10:11',
        'Deuteronomy 18:15-19',
        'Deuteronomy 29:1',
      ],
    },
    {
      id: 'tablets-remembered',
      label: 'The Tablets in the Ark',
      position: at(48, 86, 5),
      maxDistance: 42,
      body: 'At the dedication of Solomon’s Temple in Jerusalem, the account identifies the two stone tablets in the ark as those Moses placed there at Horeb when the Lord made a covenant with Israel. The Temple dedication happens centuries later and in Jerusalem; this stop traces the memory of the tablets.',
      refs: ['1 Kings 8:9', '2 Chronicles 5:10'],
    },
    {
      id: 'poets',
      label: 'Sinai in Song and Prayer',
      position: at(-28, -115, 4),
      maxDistance: 35,
      body: 'Biblical poetry recalls the Lord coming from Sinai and the earth trembling before him. Psalm 106 remembers the calf at Horeb and Moses standing in the breach. Nehemiah’s prayer remembers God descending on Sinai and giving just laws. These passages interpret and remember the events rather than narrate new visits.',
      refs: [
        'Deuteronomy 33:2',
        'Judges 5:4-5',
        'Psalm 68:7-8',
        'Psalm 68:17',
        'Psalm 106:19-23',
        'Nehemiah 9:13-14',
      ],
    },
    {
      id: 'malachi',
      label: 'Remember the Law of Moses',
      position: at(64, 38, 3),
      maxDistance: 36,
      body: 'Malachi closes with a call to remember the law given through Moses at Horeb, followed by the promise of Elijah before the day of the Lord. The passage brings the two great figures associated with this mountain into the same closing appeal.',
      refs: ['Malachi 4:4-6'],
    },
    {
      id: 'stephen',
      label: 'Stephen Recalls the Wilderness',
      position: at(-70, 36, 4),
      maxDistance: 40,
      body: 'In Jerusalem, Stephen recounts Moses’ encounter at the burning bush in the wilderness of Mount Sinai, his commission, the assembly in the wilderness, the calf and the tent of testimony. The speech is a later witness to these events, not an episode physically taking place here.',
      refs: ['Acts 7:30-44'],
    },
    {
      id: 'galatians',
      label: 'Paul’s Covenant Comparison',
      position: at(0, 68, 4),
      maxDistance: 42,
      body: 'Paul uses Hagar and Sarah in a covenant comparison. He associates Hagar with Mount Sinai in Arabia and with the present Jerusalem, contrasting it with the Jerusalem above. His argument is theological; this reading stop does not use it to settle the mountain’s disputed modern location.',
      refs: ['Galatians 4:21-31'],
    },
    {
      id: 'hebrews',
      label: 'Sinai and Mount Zion',
      position: at(-3, -150, 4),
      maxDistance: 40,
      body: 'Hebrews contrasts the mountain of fire, darkness, storm and fearful hearing with Mount Zion, the heavenly Jerusalem and Jesus, mediator of a new covenant. Sinai is recalled without being named in this passage. The comparison ends with a call to gratitude and reverent worship.',
      refs: ['Hebrews 12:18-29'],
    },
  ],
};

// The opening view takes in the mountain above the people at its foot.
for (const stop of [
  SINAI.vantages[0],
  ...SINAI.events.filter((e) => ['revelation', 'commandments'].includes(e.id)),
])
  stop.lookAt = at(0, -130, 18);
