// Generated by scripts/humans/package_elah_characters.mjs. See docs/elah-character-assets.md.
export const ELAH_CHARACTER_ASSETS = [
  {
    "id": "human-david",
    "url": "/assets/scenes/elah/characters/david-8d3e67692c2d.glb",
    "size": 5276388,
    "hash": "8d3e6769",
    "sha256": "8d3e67692c2d3245e3ee5001d08028e01041dd0a1a2b71c0dd22a4b1d6ca2ee9",
    "source": "makehuman-community-cc0",
    "license": "CC0",
    "bodyHeightMeters": 1.65,
    "triangles": [
      58174,
      10919
    ]
  },
  {
    "id": "human-goliath",
    "url": "/assets/scenes/elah/characters/goliath-7bb6d76cb451.glb",
    "size": 4199300,
    "hash": "7bb6d76c",
    "sha256": "7bb6d76cb4512549cdee0e17f7eff71d4276f6f358912f9f2d0522127105d011",
    "source": "makehuman-community-cc0",
    "license": "CC0",
    "bodyHeightMeters": 2.9,
    "triangles": [
      61139,
      12454
    ]
  },
  {
    "id": "human-shield-bearer",
    "url": "/assets/scenes/elah/characters/shield-bearer-5830987e203f.glb",
    "size": 3164828,
    "hash": "5830987e",
    "sha256": "5830987e203fda335bf95b20c6cb549dcb26b67e17191bb0fc27aefe58d04b58",
    "source": "makehuman-community-cc0",
    "license": "CC0",
    "bodyHeightMeters": 1.75,
    "triangles": [
      55707,
      11245
    ]
  }
];
