export const SCENE_SOURCES_DATA = {
  sinai: [
    { id: 'SIN-NAMES', claim: 'Sinai and Horeb', certainty: 'attested', detail: 'The biblical narratives use both names for the mountain of God and the covenant setting. Their traditional identification with the same mountain or region does not establish its modern location. The Atlas point follows the southern Sinai tradition.', source: 'Exodus 3:1; 19:1-2; Deuteronomy 5:2; 1 Kings 19:8. NABRE note on Exodus 3:1, biblegateway.com/passage/?search=Exodus+3%3A1&version=NABRE.' },
    { id: 'SIN-MOSES', claim: 'The Call, Covenant and Renewal', certainty: 'attested', detail: 'The bush, signs, Aaron’s reunion, water at Horeb, Jethro’s visit, covenant, tablets, calf, intercession and renewed covenant follow Exodus. Rephidim and Horeb are connected in Exodus 17; their distances are not reproduced. The earlier tent outside the camp is kept distinct from the later sanctuary.', source: 'Exodus 3–4; 17–24; 25–34.' },
    { id: 'SIN-SANCTUARY', claim: 'The Sanctuary and Departure', certainty: 'attested', detail: 'Construction, consecration, priestly ministry, law, gifts, census, Passover, trumpets and departure draw on Exodus, Leviticus and Numbers. Numbers 7–9 recounts some events earlier than the census. The representative camp and simplified outdoor sanctuary do not reproduce the size of the full encampment.', source: 'Exodus 35–40; Leviticus 1:1; 8–10; 16; 19; 24–27; Numbers 1–10.' },
    { id: 'SIN-ELIJAH', claim: 'Elijah’s Visit', certainty: 'attested', detail: 'The cave, wind, earthquake, fire, quiet voice and commission follow 1 Kings. Scripture does not identify Elijah’s cave with Moses’ cleft. The two settings are separate in this environment, and the earlier camp disappears.', source: '1 Kings 19:1-18.' },
    { id: 'SIN-RECOLLECTION', claim: 'Later Scripture Remembers Sinai', certainty: 'attested', detail: 'Deuteronomy, the Temple dedication, poetry, Nehemiah, Malachi, Acts, Galatians and Hebrews remember or interpret Sinai. Reading stops distinguish these later recollections from events physically set on the mountain.', source: 'Deuteronomy 1; 4–5; 9–10; 18; 33; 1 Kings 8:9; 2 Chronicles 5:10; Judges 5:4-5; Psalms 68; 106; Nehemiah 9:13-14; Malachi 4:4-6; Acts 7:30-44; Galatians 4:21-31; Hebrews 12:18-29.' },
    { id: 'SIN-ART', claim: 'An Interpretive Mountain Landscape', certainty: 'inferred', detail: 'The granite forms, paths, cave, tents, costumes, weather and figures are authored scenery. Light, cloud and fire suggest the text without a human depiction of God. Difficult judgments are narrated without graphic imagery. No precise date, mountain identification, scale of the camp or physical appearance of the encounters is claimed.', source: 'Visual interpretation informed by the biblical passages cited at each stop.' },
  ],
  bethlehem: [
    { id: 'BET-TEXT-01', claim: 'Bethlehem, the Manger and the Shepherds', certainty: 'attested', detail: 'Luke names Bethlehem, Mary, Joseph, a wrapped infant in a manger, and shepherds watching their flock at night. These narrative details guide the scene; they do not supply an excavated plan.', source: 'Luke 2:1-20.' },
    { id: 'BET-HOUSE-01', claim: 'The Magi Visit a House', certainty: 'attested', detail: 'Matthew describes a house, the child with Mary, and three named gifts. The number of visitors and the interval after the birth are unstated. Their visit is staged separately; three figures are a compositional choice.', source: 'Matthew 2:1-12.' },
    { id: 'BET-CAVE-01', claim: 'The Shelter and the Cave Tradition', certainty: 'inferred', detail: 'The Gospel does not describe the building around the manger. An early Christian tradition locates the birth in a cave at Bethlehem. This rock-backed shelter evokes that tradition without claiming to reproduce the Nativity grotto.', source: 'UNESCO World Heritage Centre, Birthplace of Jesus: Church of the Nativity and the Pilgrimage Route, Bethlehem (whc.unesco.org/en/list/1433/); Luke 2:7.' },
    { id: 'BET-PLAN-01', claim: 'A Village in Limestone Hill Country', certainty: 'inferred', detail: 'The houses, well, paths, olive groves and pasture form an illustrative village in Bethlehem’s hill-country setting. The terrain is authored, not surveyed; no precise location is claimed for the shepherds’ field or the family’s house.', source: 'UNESCO World Heritage Centre, Bethlehem, property 1433; Luke 2:8-16.' },
    { id: 'BET-DATE-01', claim: 'The Days of Herod', certainty: 'inferred', detail: 'Matthew places the birth during Herod’s reign. The displayed range is approximate; the scene does not assert an exact year, season, census reconstruction or explanation for the star.', source: 'Matthew 2:1; Luke 2:1-2.' },
  ],
  capernaum: [
    {
      id: 'CAP-ARCH-BASALT-01',
      claim: 'Basalt Domestic Architecture',
      detail: 'Village houses built from unworked local black basalt fieldstones bonded with mud and clay rather than ashlar limestone.',
      certainty: 'attested',
      source: 'Corbo (1975), Cafarnao I: Gli edifici della città; Loffreda (1993), Recovering Capharnaum.',
    },
    {
      id: 'CAP-BOAT-GINOSAR-01',
      claim: 'Sea of Galilee Fishing Boat',
      detail: 'Standard commercial hull 8.27m length, 2.30m beam, 1.25m depth, carvel mortise-and-tenon construction with mixed cedar/oak timbers.',
      certainty: 'attested',
      source: 'Wachsmann (1995), The Sea of Galilee Boat; Israel Antiquities Authority Report.',
    },
    {
      id: 'CAP-ARCH-ROOF-01',
      claim: 'Mud-and-Reed Domestic Roofs',
      detail: 'Rafter beams carrying packed brushwood, reeds, and rolled earthen marl terrace, without terracotta tiles.',
      certainty: 'attested',
      source: 'Mark 2:4; Loffreda (1993); cf. Luke 5:19, which says “through the tiles”, written for readers who knew tiled roofs.',
    },
    {
      id: 'CAP-ARCH-SYN-01',
      claim: 'Basalt Foundations Beneath the Synagogue',
      detail: 'Basalt walls and a basalt pavement beneath the white limestone synagogue (late 4th–6th century), taken by the excavators to be the synagogue of Jesus’ day; others read them as a later phase or an open paved area. The hall’s benches, columns and plan here are modelled on Magdala and Gamla.',
      certainty: 'probable',
      source: 'Corbo (1975); Loffreda, Recovering Capharnaum (1985; 2nd ed. 1993); Luke 7:5.',
    },
    {
      id: 'CAP-SYN-INTERIOR-01',
      claim: 'The Hall Inside',
      detail: 'Stepped stone benches on all four sides, columns carrying the roof, a table at the centre for the scroll, and walls plastered and painted in coloured panels, as in the first-century synagogues excavated at Magdala and Gamla. Capernaum’s own first-century interior is not preserved.',
      certainty: 'inferred',
      source: 'Aviam, “The Decorated Stone from the Synagogue at Migdal”, Novum Testamentum 55 (2013); Syon & Yavor, Gamla II: The Architecture (IAA Reports 44, 2010); Levine, The Ancient Synagogue (2nd ed. 2005); the Theodotos inscription (CIJ 1404).',
    },
    {
      id: 'CAP-SYN-SABBATH-01',
      claim: 'The Unclean Spirit Rebuked',
      detail: 'Jesus teaching on a sabbath in the synagogue at Capernaum and rebuking an unclean spirit, as Mark and Luke tell it. Teaching seated follows Luke 4:20; the poses, clothing and seating (including where the women sit) are reconstruction.',
      certainty: 'illustrative',
      source: 'Mark 1:21-28; Luke 4:31-37; Luke 4:16-20; Luke 13:10-17; John 6:59.',
    },
    {
      id: 'CAP-EVENTS-01',
      claim: 'Where Each Event Happened',
      detail: 'The text places the synagogue (Mark 1:21; John 6:59), the house of Simon and Andrew and its door (Mark 1:29-33; 2:1-4; 9:33), the tax booth beside the sea (Mark 2:13-14), and the centurion and the temple tax “in Capernaum” (Matthew 8:5; 17:24). The scene chooses which stretch of shore (Mark 1:16), which street, the shore street for Mark 5:21-34 (“beside the sea”) and the pier for Matthew 17:27. One event is staged at a time.',
      certainty: 'inferred',
      source: 'Mark 1-2, 5, 9; Matthew 8, 17; Luke 4-5, 7; John 6.',
    },
    {
      id: 'CAP-FISH-BARBEL-01',
      claim: 'The Fish That Takes a Hook',
      detail: 'Tilapia, sold to pilgrims as “St Peter’s fish”, feed on plankton and are netted, not hooked; the lake’s barbels are predators taken on hook and line, so the fish of Matthew 17:27 is shown as a barbel.',
      certainty: 'probable',
      source: 'Nun (1989), The Sea of Galilee and Its Fishermen in the New Testament.',
    },
    {
      id: 'CAP-COIN-TYRE-01',
      claim: 'A Shekel for Two',
      detail: 'The half-shekel temple tax (Exodus 30:13) was paid in the silver of Tyre; a Tyrian shekel, a four-drachma stater, paid it for two men — “for me and for yourself”.',
      certainty: 'attested',
      source: 'Exodus 30:11-16; Matthew 17:24-27; Mishnah Bekhorot 8:7; Tosefta Ketubbot 13:3.',
    },
    {
      id: 'CAP-TZITZIT-01',
      claim: 'Fringes with a Cord of Blue',
      detail: 'Tassels on the four corners of the outer garment, each with a cord of blue, which Matthew and Luke say the woman touched. The practice is written; the tassels’ exact form here is reconstruction.',
      certainty: 'attested',
      source: 'Numbers 15:38-39; Deuteronomy 22:12; Matthew 9:20; 14:36; 23:5; Luke 8:44.',
    },
    {
      id: 'CAP-CENTURION-01',
      claim: 'The Centurion’s Staff and Sword',
      detail: 'A vine staff as the badge of a centurion’s rank, and his sword worn on the left, as Roman centurions are shown. Galilee was Herod Antipas’s; whether his troops followed Roman practice this closely is not known.',
      certainty: 'inferred',
      source: 'Pliny, Natural History 14.19; Tacitus, Annals 1.23; tombstone of the centurion M. Favonius Facilis (Colchester); Luke 7:1-10.',
    },
    {
      id: 'CAP-FISH-NETS-01',
      claim: 'Lakeside Net Drying Racks & Weights',
      detail: 'Circular cast nets (amphiblestron) and trammel/seine nets (sagene) with stone weights and cork floats.',
      certainty: 'attested',
      source: 'Nun (1989), The Sea of Galilee and Its Fishermen in the New Testament; Mark 1:16–19.',
    },
    {
      id: 'CAP-PROP-POTTERY-01',
      claim: 'Galilean Domestic Ceramics',
      detail: 'Earthenware storage jars, cooking pots with grooved rims, and Herodian spouted oil lamps manufactured in Kfar Hananya.',
      certainty: 'attested',
      source: 'Adan-Bayewitz (1993), Common Pottery in Roman Galilee.',
    },
    {
      id: 'CAP-HARB-NUN-01',
      claim: 'Basalt Piers and Mooring Stones',
      detail: 'A promenade with piers of basalt fieldstone and pierced mooring stones along the Capernaum waterfront; the date of these works is debated (Roman, possibly later), so only two modest piers are shown.',
      certainty: 'probable',
      source: 'Nun (1989), The Sea of Galilee: Newly Discovered Harbours from New Testament Days; Nun, "Ports of Galilee", BAR 25:4 (1999).',
    },
    {
      id: 'CAP-GEO-HORIZON-01',
      claim: 'The Skyline from the Shore',
      detail: 'Terrain and horizon computed from SRTM elevation data: the Golan wall across the water to the east, Arbel to the south-west, the Korazim slope behind. Hermon, Tabor and Meron are hidden from here by nearer ground and are not drawn.',
      certainty: 'attested',
      source: 'SRTM elevation (AWS Terrain Tiles), checked against OpenTopoData srtm30m; scripts/build-capernaum-landscape.py.',
    },
    {
      id: 'CAP-LIFE-01',
      claim: 'Flocks, Donkeys and Poultry',
      detail: 'Mixed flocks of black goats and fat-tailed sheep folded behind dry-stone walls; donkeys as the pack animals of the road; hens and roosters kept in village courtyards.',
      certainty: 'attested',
      source: 'Borowski (1998), Every Living Thing: Daily Use of Animals in Ancient Israel; Matthew 23:37; John 10:1-16.',
    },
    {
      id: 'CAP-ARCH-PARAPET-01',
      claim: 'Roof Parapets',
      detail: 'A parapet round a flat roof in use, as Deuteronomy 22:8 asks; not attested at Capernaum. Height (0.8 m) from the later rabbinic minimum of ten handbreadths.',
      certainty: 'inferred',
      source: 'Deuteronomy 22:8; Sifre Deuteronomy 229; b. Bava Kamma 15b; comparative village architecture.',
    },
    {
      id: 'CAP-SEASON-01',
      claim: 'Late Spring',
      detail: 'The season shown — barley harvested, wheat ripening, oleander and thistles in flower — is a choice that fits Mark 2:23, not a date the text gives for these chapters.',
      certainty: 'illustrative',
      source: 'Mark 2:23; agricultural calendar of the Gezer Calendar and Mishnah; Josephus, War 3.516-521 on Gennesaret.',
    },
  ],
  'second-temple': [
    {
      id: 'TEM-MISHNAH-MIDDOT',
      claim: 'Precinct Proportions & Steps',
      detail: 'The 35-acre platform, outer court colonnades, soreg boundary, Court of the Women, and 15 curved steps leading to the inner court.',
      certainty: 'attested',
      source: 'Mishnah Middot; Josephus, Antiquities 15 & Jewish War 5.',
    },
    {
      id: 'TEM-EVENTS-01',
      claim: 'Where Each Event Happened',
      detail: 'The text names the sanctuary and the people outside (Luke 1), the treasury (Mark 12:41; John 8:20), Solomon’s colonnade (John 10:23), the gate called Beautiful (Acts 3:2) and the temple courts. The scene chooses the rest: the Nicanor Gate for the presentation, Solomon’s Portico for the boy among the teachers, the south of the outer court for the traders, the gate into the Court of the Women for the Beautiful Gate. One event is staged at a time.',
      certainty: 'inferred',
      source: 'Luke 1-2; Mark 11-12; John 2, 8, 10; Acts 3, 21.',
    },
    {
      id: 'TEM-NICANOR-01',
      claim: 'Purification at the Nicanor Gate',
      detail: 'Mothers after childbirth were purified at the Nicanor Gate, at the top of the fifteen steps — the setting for Mary’s offering and Simeon’s blessing.',
      certainty: 'attested',
      source: 'Mishnah Sotah 1:5; Leviticus 12:6-8; Luke 2:22-24.',
    },
    {
      id: 'TEM-TREASURY-01',
      claim: 'Thirteen Trumpet-Shaped Chests',
      detail: 'The offering chests in the Court of the Women were shaped like trumpets (shofarot), thirteen of them, each labelled for the money it took. Their placement along the wall here is reconstruction.',
      certainty: 'attested',
      source: 'Mishnah Shekalim 6:1, 6:5; Mark 12:41-44.',
    },
    {
      id: 'TEM-TYRE-01',
      claim: 'Money-Changers and Tyrian Silver',
      detail: 'The half-shekel temple tax had to be paid in Tyrian silver, which is why changers set up in the courts; the animals for the offerings were sold there too.',
      certainty: 'attested',
      source: 'Exodus 30:13; Tosefta Ketubbot 13:3; Mishnah Bekhorot 8:7; John 2:13-16.',
    },
    {
      id: 'TEM-JOHN8-01',
      claim: 'The Woman Caught in Adultery',
      detail: 'John 7:53–8:11 is absent from the earliest Greek manuscripts of John and printed in brackets in many Bibles; the scene says so rather than presenting it without comment.',
      certainty: 'attested',
      source: 'Metzger, A Textual Commentary on the Greek New Testament (2nd ed. 1994).',
    },
    {
      id: 'TEM-ANTONIA-01',
      claim: 'The Antonia and Its Stairs',
      detail: 'A Roman cohort garrisoned the Antonia at the north-west corner of the courts, with stairs down into the porticoes — how the tribune reached Paul so quickly.',
      certainty: 'attested',
      source: 'Josephus, Jewish War 5.238-247; Acts 21:31-40.',
    },
    {
      id: 'TEM-HANUKKAH-01',
      claim: 'The Feast of Dedication',
      detail: 'Hanukkah remembered Judas Maccabeus’s cleansing of the temple and the new altar dedicated in 164 BC, kept for eight days each winter.',
      certainty: 'attested',
      source: '1 Maccabees 4:36-59; Josephus, Antiquities 12.316-325; John 10:22.',
    },
    {
      id: 'TEM-MOTION-01',
      claim: 'How the People Move',
      detail: 'The courts’ crowd and most of the staged casts move by captured human motion (Adobe Mixamo) fitted to each character; the few gestures that must land on something are authored. Gestures and postures are modern captures, not evidence of ancient custom.',
      certainty: 'illustrative',
      source: 'Adobe Mixamo motion library, retargeted in src/components/scene/sceneMixamo.js.',
    },
  ],
  'mount-of-olives': [
    {
      id: 'OLV-TERRAIN-01',
      claim: 'The Ground and the Far Skyline',
      detail: 'The hillside, the Kidron and the plateau across it are elevation data: SRTM-derived terrain tiles sampled every 15 m within 1.2 km of Gethsemane. The skyline is traced from the same data at true bearings — the hills west of the city from the slope, and from the summit the Judean wilderness, the Dead Sea where the line of sight clears the desert, and the Moab plateau. The data is of the modern surface; the Temple platform is levelled to its court.',
      certainty: 'attested',
      source: 'AWS Terrain Tiles (terrarium), derived from NASA SRTM; baked by scripts/build-olivet-landscape.py.',
    },
    {
      id: 'OLV-TEMPLE-01',
      claim: 'The Temple Seen from the Mount',
      detail: 'The platform’s walls follow the edge of the plateau in the elevation data; the sanctuary stands on the rock under the Dome of the Rock, facing east, built to the same Mishnah Middot measurements as the Temple scene; the Antonia at the north-west corner; Herod’s three towers on the western skyline. The priest burning the red heifer on the Mount could see the sanctuary’s door over the low eastern wall.',
      certainty: 'inferred',
      source: 'Mishnah Middot 1:3, 2:4, 4:6-7; Josephus, War 5.184-247; Antiquities 15.410-420; Mark 13:1-3.',
    },
    {
      id: 'OLV-GETHSEMANE-01',
      claim: 'Gethsemane',
      detail: 'John calls it a garden across the Kidron; Mark and Matthew name it Gethsemane, "oil press". Its place at the foot of the Mount is the tradition of the Church of All Nations, attested from the fourth century. The wall, gates, press yard and trees are reconstruction; the oldest living olives there have been dated to the twelfth century.',
      certainty: 'inferred',
      source: 'John 18:1-2; Mark 14:32; Matthew 26:36; Bernabei et al., Journal of Cultural Heritage (2015), on the Gethsemane olives.',
    },
    {
      id: 'OLV-TOMBS-01',
      claim: 'The Kidron Monuments',
      detail: 'Absalom’s Pillar, the tomb of the Bene Hezir (a priestly family named in its Hebrew inscription) and the monolith called Zechariah’s tomb stand cut from the rock at the foot of the Mount facing the Temple. Hezir’s tomb and Zechariah’s are of the second or first century BC; Absalom’s Pillar of the first century AD.',
      certainty: 'attested',
      source: '1 Chronicles 24:15; 2 Samuel 18:18; Matthew 23:29; Avigad, Ancient Monuments in the Kidron Valley (1954).',
    },
    {
      id: 'OLV-ROAD-01',
      claim: 'The Road Down',
      detail: 'Luke places the shouting on the descent of the Mount (19:37) and the weeping where the city came into view (19:41). The line of the first-century road is not known; this one follows the traditional steep descent from the ridge to Gethsemane.',
      certainty: 'inferred',
      source: 'Luke 19:29-44; Mark 11:1-11; John 12:12-15.',
    },
    {
      id: 'OLV-PASSOVER-01',
      claim: 'The Mount at Passover',
      detail: 'Pilgrims camped round the city at the feasts and Luke says Jesus lodged on this hill (21:37); the barley harvest began, with the first sheaf waved in the Temple; the fig trees were putting out leaves; beacons on the Mount announced the new month. The camps, flocks and fields shown are reconstruction.',
      certainty: 'inferred',
      source: 'Luke 21:37-38; Leviticus 23:10-14; Mark 11:13, 13:28; Mishnah Rosh Hashanah 2:2-4; Josephus, War 6.422-425.',
    },
    {
      id: 'OLV-ASCENSION-01',
      claim: 'Where He Was Taken Up',
      detail: 'Acts places the ascension on the Mount called Olivet, a Sabbath day’s journey from the city; Luke’s gospel says he led them out as far as Bethany. The scene stages it on the summit, where the fourth-century church of the Ascension stood.',
      certainty: 'inferred',
      source: 'Acts 1:9-12; Luke 24:50-51.',
    },
  ],
  caesarea: [
    {
      id: 'CAES-SEBASTOS-01',
      claim: 'Herodian Sebastos Harbor & Praetorium',
      detail: 'Roman administrative center, harbor breakwaters, and governors residence hosting Paul’s witness.',
      certainty: 'illustrative',
      source: 'Acts 23–27; Raban (1989), Caesarea Maritima.',
    },
  ],
  tabernacle: [
    {
      id: 'TAB-EXODUS-SPEC',
      claim: 'Biblical Cubit Dimensions',
      detail: 'Exodus 25–40 text specifications (1 cubit = 0.5m). 100 × 50 cubit court, 48 acacia boards in 96 silver sockets.',
      certainty: 'attested',
      source: 'Exodus 25–40 scriptural text.',
    },
  ],
};
