export const SCENE_SOURCES_DATA = {
  capernaum: [
    {
      id: 'CAP-ARCH-BASALT-01',
      claim: 'Basalt Domestic Architecture',
      detail: 'Village houses built from unworked local black basalt fieldstones bonded with mud and clay rather than ashlar limestone.',
      certainty: 'attested',
      source: 'Corbo (1975), Cafarnao I: Gli edifici della città; Loffreda (1993), Recovering Capharnaum.',
    },
    {
      id: 'CAP-BOAT-GINOSAR-01',
      claim: 'Sea of Galilee Fishing Boat',
      detail: 'Standard commercial hull 8.27m length, 2.30m beam, 1.25m depth, carvel mortise-and-tenon construction with mixed cedar/oak timbers.',
      certainty: 'attested',
      source: 'Wachsmann (1995), The Sea of Galilee Boat; Israel Antiquities Authority Report.',
    },
    {
      id: 'CAP-ARCH-ROOF-01',
      claim: 'Mud-and-Reed Domestic Roofs',
      detail: 'Rafter beams carrying packed brushwood, reeds, and rolled earthen marl terrace, without terracotta tiles.',
      certainty: 'attested',
      source: 'Mark 2:4; Loffreda (1993); cf. Luke 5:19, which says “through the tiles”, written for readers who knew tiled roofs.',
    },
    {
      id: 'CAP-ARCH-SYN-01',
      claim: 'Basalt Foundations Beneath the Synagogue',
      detail: 'Basalt walls and a basalt pavement beneath the white limestone synagogue (late 4th–6th century), taken by the excavators to be the synagogue of Jesus’ day; others read them as a later phase or an open paved area. The hall’s benches, columns and plan here are modelled on Magdala and Gamla.',
      certainty: 'probable',
      source: 'Corbo (1975); Loffreda, Recovering Capharnaum (1985; 2nd ed. 1993); Luke 7:5.',
    },
    {
      id: 'CAP-SYN-INTERIOR-01',
      claim: 'The Hall Inside',
      detail: 'Stepped stone benches on all four sides, columns carrying the roof, a table at the centre for the scroll, and walls plastered and painted in coloured panels, as in the first-century synagogues excavated at Magdala and Gamla. Capernaum’s own first-century interior is not preserved.',
      certainty: 'inferred',
      source: 'Aviam, “The Decorated Stone from the Synagogue at Migdal”, Novum Testamentum 55 (2013); Syon & Yavor, Gamla II: The Architecture (IAA Reports 44, 2010); Levine, The Ancient Synagogue (2nd ed. 2005); the Theodotos inscription (CIJ 1404).',
    },
    {
      id: 'CAP-SYN-SABBATH-01',
      claim: 'The Unclean Spirit Rebuked',
      detail: 'Jesus teaching on a sabbath in the synagogue at Capernaum and rebuking an unclean spirit, as Mark and Luke tell it. Teaching seated follows Luke 4:20; the poses, clothing and seating (including where the women sit) are reconstruction.',
      certainty: 'illustrative',
      source: 'Mark 1:21-28; Luke 4:31-37; Luke 4:16-20; Luke 13:10-17; John 6:59.',
    },
    {
      id: 'CAP-FISH-NETS-01',
      claim: 'Lakeside Net Drying Racks & Weights',
      detail: 'Circular cast nets (amphiblestron) and trammel/seine nets (sagene) with stone weights and cork floats.',
      certainty: 'attested',
      source: 'Nun (1989), The Sea of Galilee and Its Fishermen in the New Testament; Mark 1:16–19.',
    },
    {
      id: 'CAP-PROP-POTTERY-01',
      claim: 'Galilean Domestic Ceramics',
      detail: 'Earthenware storage jars, cooking pots with grooved rims, and Herodian spouted oil lamps manufactured in Kfar Hananya.',
      certainty: 'attested',
      source: 'Adan-Bayewitz (1993), Common Pottery in Roman Galilee.',
    },
    {
      id: 'CAP-HARB-NUN-01',
      claim: 'Basalt Piers and Mooring Stones',
      detail: 'A promenade with piers of basalt fieldstone and pierced mooring stones along the Capernaum waterfront; the date of these works is debated (Roman, possibly later), so only two modest piers are shown.',
      certainty: 'probable',
      source: 'Nun (1989), The Sea of Galilee: Newly Discovered Harbours from New Testament Days; Nun, "Ports of Galilee", BAR 25:4 (1999).',
    },
    {
      id: 'CAP-GEO-HORIZON-01',
      claim: 'The Skyline from the Shore',
      detail: 'Terrain and horizon computed from SRTM elevation data: the Golan wall across the water to the east, Arbel to the south-west, the Korazim slope behind. Hermon, Tabor and Meron are hidden from here by nearer ground and are not drawn.',
      certainty: 'attested',
      source: 'SRTM elevation (AWS Terrain Tiles), checked against OpenTopoData srtm30m; scripts/build-capernaum-landscape.py.',
    },
    {
      id: 'CAP-LIFE-01',
      claim: 'Flocks, Donkeys and Poultry',
      detail: 'Mixed flocks of black goats and fat-tailed sheep folded behind dry-stone walls; donkeys as the pack animals of the road; hens and roosters kept in village courtyards.',
      certainty: 'attested',
      source: 'Borowski (1998), Every Living Thing: Daily Use of Animals in Ancient Israel; Matthew 23:37; John 10:1-16.',
    },
    {
      id: 'CAP-ARCH-PARAPET-01',
      claim: 'Roof Parapets',
      detail: 'A parapet round a flat roof in use, as Deuteronomy 22:8 asks; not attested at Capernaum. Height (0.8 m) from the later rabbinic minimum of ten handbreadths.',
      certainty: 'inferred',
      source: 'Deuteronomy 22:8; Sifre Deuteronomy 229; b. Bava Kamma 15b; comparative village architecture.',
    },
    {
      id: 'CAP-SEASON-01',
      claim: 'Late Spring',
      detail: 'The season shown — barley harvested, wheat ripening, oleander and thistles in flower — is a choice that fits Mark 2:23, not a date the text gives for these chapters.',
      certainty: 'illustrative',
      source: 'Mark 2:23; agricultural calendar of the Gezer Calendar and Mishnah; Josephus, War 3.516-521 on Gennesaret.',
    },
  ],
  'second-temple': [
    {
      id: 'TEM-MISHNAH-MIDDOT',
      claim: 'Precinct Proportions & Steps',
      detail: 'The 35-acre platform, outer court colonnades, soreg boundary, Court of the Women, and 15 curved steps leading to the inner court.',
      certainty: 'attested',
      source: 'Mishnah Middot; Josephus, Antiquities 15 & Jewish War 5.',
    },
  ],
  caesarea: [
    {
      id: 'CAES-SEBASTOS-01',
      claim: 'Herodian Sebastos Harbor & Praetorium',
      detail: 'Roman administrative center, harbor breakwaters, and governors residence hosting Paul’s witness.',
      certainty: 'illustrative',
      source: 'Acts 23–27; Raban (1989), Caesarea Maritima.',
    },
  ],
  tabernacle: [
    {
      id: 'TAB-EXODUS-SPEC',
      claim: 'Biblical Cubit Dimensions',
      detail: 'Exodus 25–40 text specifications (1 cubit = 0.5m). 100 × 50 cubit court, 48 acacia boards in 96 silver sockets.',
      certainty: 'attested',
      source: 'Exodus 25–40 scriptural text.',
    },
  ],
};
