// Generated by scripts/humans/package_characters.mjs. Source notices accompany the GLBs.
export const HUMAN_MODEL_ASSETS = [
  {
    "id": "human-artisan",
    "url": "/assets/scenes/shared/humans/artisan-ba7d2345f355.glb",
    "size": 5712656,
    "hash": "ba7d2345",
    "sha256": "ba7d2345f355b9acf1db64a2b1743aab60f75c8a37b780bab6165aad83be143c",
    "source": "makehuman-community-cc0",
    "license": "CC0",
    "triangles": [
      61136,
      10998
    ]
  },
  {
    "id": "human-villager",
    "url": "/assets/scenes/shared/humans/villager-4b0036370342.glb",
    "size": 4587528,
    "hash": "4b003637",
    "sha256": "4b0036370342339c13fc6c95e173136d03246761aec00c99e716a7f0b807429a",
    "source": "makehuman-community-cc0",
    "license": "CC0",
    "triangles": [
      59150,
      10641
    ]
  },
  {
    "id": "human-traveler",
    "url": "/assets/scenes/shared/humans/traveler-7488b1ff33e6.glb",
    "size": 4433700,
    "hash": "7488b1ff",
    "sha256": "7488b1ff33e64c4812a85139ffcbfbb25b7c04a2647ae5b54050f8106f519764",
    "source": "makehuman-community-cc0",
    "license": "CC0",
    "triangles": [
      53036,
      9540
    ]
  }
];
