// Generated by scripts/humans/package_characters.mjs. Source notices accompany the GLBs.
export const TABLEAU_MODEL_ASSETS = [
  {
    "id": "human-jesus",
    "url": "/assets/scenes/shared/humans/jesus-b3324a0b886c.glb",
    "size": 5909528,
    "hash": "b3324a0b",
    "sha256": "b3324a0b886cc7ac8d6796d877e53189d1c6ad7314d78c74423e1b4ea6c0a9db",
    "source": "makehuman-community-cc0",
    "license": "CC0",
    "triangles": [
      59659,
      10731
    ]
  }
];
