// Generated by scripts/humans/package_characters.mjs. Source notices accompany the GLBs.
export const TABLEAU_MODEL_ASSETS = [
  {
    "id": "human-jesus",
    "url": "/assets/scenes/shared/humans/jesus-b3324a0b886c.glb",
    "size": 5909528,
    "hash": "b3324a0b",
    "sha256": "b3324a0b886cc7ac8d6796d877e53189d1c6ad7314d78c74423e1b4ea6c0a9db",
    "source": "makehuman-community-cc0",
    "license": "CC0",
    "triangles": [
      59659,
      10731
    ]
  },
  {
    "id": "human-matthew",
    "url": "/assets/scenes/shared/humans/matthew-d509ab3c2569.glb",
    "size": 4134508,
    "hash": "d509ab3c",
    "sha256": "d509ab3c25693dbdcae1427dc97b32dbc3345c310d4e6b384f0fe8b342758b6c",
    "source": "makehuman-community-cc0",
    "license": "CC0",
    "triangles": [
      57210,
      10291
    ]
  }
];
