// Recorded foley. Generated by scripts/prepare-scene-audio.py.
// Attribution: /assets/scenes/shared/audio/CREDITS.txt
export const SCENE_AUDIO_ASSETS = [
  {
    "id": "snd-step-stone-1",
    "url": "/assets/scenes/shared/audio/step-stone-1-369d4d8f.ogg",
    "size": 6768,
    "hash": "369d4d8f",
    "type": "step",
    "source": "Fantozzi / qubodup",
    "license": "CC0",
    "original": "Fantozzi-footsteps/flac/Fantozzi-StoneL1.flac",
    "surface": "stone"
  },
  {
    "id": "snd-step-stone-2",
    "url": "/assets/scenes/shared/audio/step-stone-2-ec839c63.ogg",
    "size": 6743,
    "hash": "ec839c63",
    "type": "step",
    "source": "Fantozzi / qubodup",
    "license": "CC0",
    "original": "Fantozzi-footsteps/flac/Fantozzi-StoneR1.flac",
    "surface": "stone"
  },
  {
    "id": "snd-step-stone-3",
    "url": "/assets/scenes/shared/audio/step-stone-3-5f07aac4.ogg",
    "size": 6500,
    "hash": "5f07aac4",
    "type": "step",
    "source": "Fantozzi / qubodup",
    "license": "CC0",
    "original": "Fantozzi-footsteps/flac/Fantozzi-StoneL2.flac",
    "surface": "stone"
  },
  {
    "id": "snd-step-stone-4",
    "url": "/assets/scenes/shared/audio/step-stone-4-326e6a23.ogg",
    "size": 6534,
    "hash": "326e6a23",
    "type": "step",
    "source": "Fantozzi / qubodup",
    "license": "CC0",
    "original": "Fantozzi-footsteps/flac/Fantozzi-StoneR2.flac",
    "surface": "stone"
  },
  {
    "id": "snd-step-stone-5",
    "url": "/assets/scenes/shared/audio/step-stone-5-77d52f6b.ogg",
    "size": 6369,
    "hash": "77d52f6b",
    "type": "step",
    "source": "Fantozzi / qubodup",
    "license": "CC0",
    "original": "Fantozzi-footsteps/flac/Fantozzi-StoneL3.flac",
    "surface": "stone"
  },
  {
    "id": "snd-step-stone-6",
    "url": "/assets/scenes/shared/audio/step-stone-6-cbdff13e.ogg",
    "size": 6786,
    "hash": "cbdff13e",
    "type": "step",
    "source": "Fantozzi / qubodup",
    "license": "CC0",
    "original": "Fantozzi-footsteps/flac/Fantozzi-StoneR3.flac",
    "surface": "stone"
  },
  {
    "id": "snd-step-sand-1",
    "url": "/assets/scenes/shared/audio/step-sand-1-47338dc3.ogg",
    "size": 7694,
    "hash": "47338dc3",
    "type": "step",
    "source": "Fantozzi / qubodup",
    "license": "CC0",
    "original": "Fantozzi-footsteps/flac/Fantozzi-SandL1.flac",
    "surface": "sand"
  },
  {
    "id": "snd-step-sand-2",
    "url": "/assets/scenes/shared/audio/step-sand-2-9955922c.ogg",
    "size": 7336,
    "hash": "9955922c",
    "type": "step",
    "source": "Fantozzi / qubodup",
    "license": "CC0",
    "original": "Fantozzi-footsteps/flac/Fantozzi-SandR1.flac",
    "surface": "sand"
  },
  {
    "id": "snd-step-sand-3",
    "url": "/assets/scenes/shared/audio/step-sand-3-610296a2.ogg",
    "size": 6590,
    "hash": "610296a2",
    "type": "step",
    "source": "Fantozzi / qubodup",
    "license": "CC0",
    "original": "Fantozzi-footsteps/flac/Fantozzi-SandL2.flac",
    "surface": "sand"
  },
  {
    "id": "snd-step-sand-4",
    "url": "/assets/scenes/shared/audio/step-sand-4-03f3aa1d.ogg",
    "size": 6479,
    "hash": "03f3aa1d",
    "type": "step",
    "source": "Fantozzi / qubodup",
    "license": "CC0",
    "original": "Fantozzi-footsteps/flac/Fantozzi-SandR2.flac",
    "surface": "sand"
  },
  {
    "id": "snd-step-sand-5",
    "url": "/assets/scenes/shared/audio/step-sand-5-f4915262.ogg",
    "size": 6251,
    "hash": "f4915262",
    "type": "step",
    "source": "Fantozzi / qubodup",
    "license": "CC0",
    "original": "Fantozzi-footsteps/flac/Fantozzi-SandL3.flac",
    "surface": "sand"
  },
  {
    "id": "snd-step-sand-6",
    "url": "/assets/scenes/shared/audio/step-sand-6-5a7f9320.ogg",
    "size": 6568,
    "hash": "5a7f9320",
    "type": "step",
    "source": "Fantozzi / qubodup",
    "license": "CC0",
    "original": "Fantozzi-footsteps/flac/Fantozzi-SandR3.flac",
    "surface": "sand"
  },
  {
    "id": "snd-step-earth-1",
    "url": "/assets/scenes/shared/audio/step-earth-1-20d6af24.ogg",
    "size": 5833,
    "hash": "20d6af24",
    "type": "step",
    "source": "Kenney",
    "license": "CC0",
    "original": "impact/Audio/footstep_grass_000.ogg",
    "surface": "earth"
  },
  {
    "id": "snd-step-earth-2",
    "url": "/assets/scenes/shared/audio/step-earth-2-af5cbf33.ogg",
    "size": 5691,
    "hash": "af5cbf33",
    "type": "step",
    "source": "Kenney",
    "license": "CC0",
    "original": "impact/Audio/footstep_grass_001.ogg",
    "surface": "earth"
  },
  {
    "id": "snd-step-earth-3",
    "url": "/assets/scenes/shared/audio/step-earth-3-2fc91ddf.ogg",
    "size": 5733,
    "hash": "2fc91ddf",
    "type": "step",
    "source": "Kenney",
    "license": "CC0",
    "original": "impact/Audio/footstep_grass_002.ogg",
    "surface": "earth"
  },
  {
    "id": "snd-step-earth-4",
    "url": "/assets/scenes/shared/audio/step-earth-4-b2e52257.ogg",
    "size": 5691,
    "hash": "b2e52257",
    "type": "step",
    "source": "Kenney",
    "license": "CC0",
    "original": "impact/Audio/footstep_grass_003.ogg",
    "surface": "earth"
  },
  {
    "id": "snd-step-timber-1",
    "url": "/assets/scenes/shared/audio/step-timber-1-d52bfaee.ogg",
    "size": 4413,
    "hash": "d52bfaee",
    "type": "step",
    "source": "Kenney",
    "license": "CC0",
    "original": "impact/Audio/footstep_wood_000.ogg",
    "surface": "timber"
  },
  {
    "id": "snd-step-timber-2",
    "url": "/assets/scenes/shared/audio/step-timber-2-134eeaa9.ogg",
    "size": 4234,
    "hash": "134eeaa9",
    "type": "step",
    "source": "Kenney",
    "license": "CC0",
    "original": "impact/Audio/footstep_wood_001.ogg",
    "surface": "timber"
  },
  {
    "id": "snd-step-timber-3",
    "url": "/assets/scenes/shared/audio/step-timber-3-b8cb8e55.ogg",
    "size": 4234,
    "hash": "b8cb8e55",
    "type": "step",
    "source": "Kenney",
    "license": "CC0",
    "original": "impact/Audio/footstep_wood_002.ogg",
    "surface": "timber"
  },
  {
    "id": "snd-step-timber-4",
    "url": "/assets/scenes/shared/audio/step-timber-4-f367a585.ogg",
    "size": 4441,
    "hash": "f367a585",
    "type": "step",
    "source": "Kenney",
    "license": "CC0",
    "original": "impact/Audio/footstep_wood_003.ogg",
    "surface": "timber"
  },
  {
    "id": "snd-step-water-1",
    "url": "/assets/scenes/shared/audio/step-water-1-f4ffa0a4.ogg",
    "size": 11089,
    "hash": "f4ffa0a4",
    "type": "step",
    "source": "Blender Foundation / Yo Frankie!",
    "license": "CC-BY-3.0",
    "original": "sfx_step_water_l.flac",
    "surface": "water"
  },
  {
    "id": "snd-step-water-2",
    "url": "/assets/scenes/shared/audio/step-water-2-0ede17cf.ogg",
    "size": 10397,
    "hash": "0ede17cf",
    "type": "step",
    "source": "Blender Foundation / Yo Frankie!",
    "license": "CC-BY-3.0",
    "original": "sfx_step_water_r.flac",
    "surface": "water"
  },
  {
    "id": "snd-wind",
    "url": "/assets/scenes/shared/audio/wind-091f1498.ogg",
    "size": 22750,
    "hash": "091f1498",
    "type": "loop",
    "source": "Blender Foundation / Yo Frankie!",
    "license": "CC-BY-3.0",
    "original": "ambient_mountains_forest_river_waterfall_wind/amb_wind_1.flac"
  },
  {
    "id": "snd-shore",
    "url": "/assets/scenes/shared/audio/shore-a8d054cd.ogg",
    "size": 170384,
    "hash": "a8d054cd",
    "type": "loop",
    "source": "RandomMind",
    "license": "CC0",
    "original": "waves.mp3"
  },
  {
    "id": "snd-surf",
    "url": "/assets/scenes/shared/audio/surf-0fc1969b.ogg",
    "size": 200820,
    "hash": "0fc1969b",
    "type": "loop",
    "source": "RandomMind",
    "license": "CC0",
    "original": "waves.mp3"
  },
  {
    "id": "snd-fire",
    "url": "/assets/scenes/shared/audio/fire-79531529.ogg",
    "size": 44387,
    "hash": "79531529",
    "type": "loop",
    "source": "qubodup",
    "license": "CC-BY-3.0",
    "original": "qubodupFireLoop.ogg"
  },
  {
    "id": "snd-bird-1",
    "url": "/assets/scenes/shared/audio/bird-1-75a07f8a.ogg",
    "size": 15072,
    "hash": "75a07f8a",
    "type": "call",
    "source": "Blender Foundation / Yo Frankie!",
    "license": "CC-BY-3.0",
    "original": "amb_bird_cricket_frog/amb_bird_1.flac"
  },
  {
    "id": "snd-bird-2",
    "url": "/assets/scenes/shared/audio/bird-2-e549eb11.ogg",
    "size": 31865,
    "hash": "e549eb11",
    "type": "call",
    "source": "Blender Foundation / Yo Frankie!",
    "license": "CC-BY-3.0",
    "original": "amb_bird_cricket_frog/amb_bird_2.flac"
  },
  {
    "id": "snd-cricket",
    "url": "/assets/scenes/shared/audio/cricket-5743ed96.ogg",
    "size": 5959,
    "hash": "5743ed96",
    "type": "call",
    "source": "Blender Foundation / Yo Frankie!",
    "license": "CC-BY-3.0",
    "original": "amb_bird_cricket_frog/amb_cricket_1.flac"
  },
  {
    "id": "snd-frog",
    "url": "/assets/scenes/shared/audio/frog-66403fd9.ogg",
    "size": 13369,
    "hash": "66403fd9",
    "type": "call",
    "source": "Blender Foundation / Yo Frankie!",
    "license": "CC-BY-3.0",
    "original": "amb_bird_cricket_frog/amb_frog_1.flac"
  }
];
