// Generated by scripts/humans/package_tabernacle_characters.mjs. See docs/tabernacle-character-assets.md.
export const TABERNACLE_CHARACTER_ASSETS = [
  {
    "id": "human-tabernacle-camp-man",
    "url": "/assets/scenes/tabernacle/characters/camp-man-7f2979971ffb.glb",
    "size": 4153072,
    "hash": "7f297997",
    "sha256": "7f2979971ffb942a16d1d3b1a3e0eb78f35f0693278a163870e08755ce3b184a",
    "source": "makehuman-community-cc0",
    "license": "CC0",
    "bodyHeightMeters": 1.7,
    "triangles": [
      50377,
      9161
    ]
  },
  {
    "id": "human-tabernacle-camp-woman",
    "url": "/assets/scenes/tabernacle/characters/camp-woman-b8b2dbe2bb4f.glb",
    "size": 4348944,
    "hash": "b8b2dbe2",
    "sha256": "b8b2dbe2bb4fb50c1ea02bb4e10174105bad0e919fce470d24abdbfb19f96bcc",
    "source": "makehuman-community-cc0",
    "license": "CC0",
    "bodyHeightMeters": 1.62,
    "triangles": [
      56831,
      10304
    ]
  },
  {
    "id": "human-tabernacle-levite",
    "url": "/assets/scenes/tabernacle/characters/levite-925c1d9267c3.glb",
    "size": 2840260,
    "hash": "925c1d92",
    "sha256": "925c1d9267c3e03223d53acd93711ca1f27f07d230984601fa329362329978de",
    "source": "makehuman-community-cc0",
    "license": "CC0",
    "bodyHeightMeters": 1.73,
    "triangles": [
      50851,
      9689
    ]
  },
  {
    "id": "human-tabernacle-priest",
    "url": "/assets/scenes/tabernacle/characters/priest-12dba274ce8a.glb",
    "size": 2947308,
    "hash": "12dba274",
    "sha256": "12dba274ce8ae1338c3a0f471f1675bf2dc8f4d36a0d1911a51d5efa31673532",
    "source": "makehuman-community-cc0",
    "license": "CC0",
    "bodyHeightMeters": 1.72,
    "triangles": [
      53429,
      10576
    ]
  },
  {
    "id": "human-tabernacle-high-priest",
    "url": "/assets/scenes/tabernacle/characters/high-priest-bfadb6dcc244.glb",
    "size": 6736232,
    "hash": "bfadb6dc",
    "sha256": "bfadb6dcc2446dcf26e6aa25150e19d67887049c690cb3111c84067863dd33be",
    "source": "makehuman-community-cc0",
    "license": "CC0",
    "bodyHeightMeters": 1.75,
    "triangles": [
      76193,
      18285
    ]
  }
];
