// Package the approved Jesus hero source into the same content-addressed
// runtime directory used by the existing scene humans, without replacing the
// shipped fallback. Input files are intentionally outside public/: the output
// becomes runtime content only after validation and hashing.
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import sharp from 'sharp';

const root = path.resolve(import.meta.dirname, '../..');
const cache = path.join(root, 'scripts/.cache/humans');
const output = path.join(root, 'public/assets/scenes/shared/humans');
const input = path.join(cache, 'jesus-v1.glb');
const metadataPath = path.join(cache, 'jesus-v1.meta.json');
const manifestPath = path.join(root, 'src/components/scene/sceneHeroAssets.js');

const requiredMetadata = ['source', 'license'];
const metadata = JSON.parse(await fs.readFile(metadataPath, 'utf8'));
for (const field of requiredMetadata) {
  if (!metadata[field] || typeof metadata[field] !== 'string') {
    throw new Error(`jesus-v1.meta.json must provide a non-empty ${field}`);
  }
}

const bytes = await fs.readFile(input);
if (bytes.toString('ascii', 0, 4) !== 'glTF' || bytes.readUInt32LE(4) !== 2) {
  throw new Error('jesus-v1.glb must be a binary glTF 2.0 file');
}
if (bytes.readUInt32LE(8) !== bytes.length) throw new Error('jesus-v1.glb header length is invalid');

const jsonLength = bytes.readUInt32LE(12);
const gltf = JSON.parse(bytes.subarray(20, 20 + jsonLength).toString());
const binary = bytes.subarray(28 + jsonLength);
if (gltf.buffers?.length !== 1 || gltf.buffers[0].uri) {
  throw new Error('Jesus hero must use one embedded GLB buffer');
}

// Rebuild buffer views after losslessly reducing embedded PNGs. Other embedded
// formats are retained unchanged; the runtime loader owns their decoder path.
const pngViews = new Set((gltf.images || [])
  .filter((image) => image.mimeType === 'image/png')
  .map((image) => image.bufferView));
const buffers = [];
let offset = 0;
for (const [index, view] of gltf.bufferViews.entries()) {
  let data = binary.subarray(view.byteOffset || 0, (view.byteOffset || 0) + view.byteLength);
  if (pngViews.has(index)) data = await sharp(data).png({ palette: true, colours: 256, effort: 10 }).toBuffer();
  view.byteOffset = offset;
  view.byteLength = data.length;
  buffers.push(data);
  offset += data.length;
  const padding = (4 - offset % 4) % 4;
  if (padding) {
    buffers.push(Buffer.alloc(padding));
    offset += padding;
  }
}
gltf.buffers[0].byteLength = offset;

// Hair cards are alpha cutouts, not translucent panes. This avoids sorting
// artifacts and keeps the hero consistent with the existing human pipeline.
for (const material of gltf.materials || []) {
  if (/hair|brow|beard|lash/i.test(material.name || '')) {
    material.alphaMode = 'MASK';
    material.alphaCutoff = material.alphaCutoff ?? 0.4;
  }
}

gltf.asset.extras = {
  ...(gltf.asset.extras || {}),
  source: metadata.source,
  license: metadata.license,
  attribution: metadata.attribution || null,
  provenance: 'docs/jesus-hero-character.md',
  historicalStatus: 'Historically informed artistic reconstruction; exact facial appearance unknown',
  authoring: metadata.authoring || 'MetaHuman/Blender to Miqra-Kodesh web hero pipeline',
};

const rawJson = Buffer.from(JSON.stringify(gltf));
const json = Buffer.concat([rawJson, Buffer.alloc((4 - rawJson.length % 4) % 4, 32)]);
const header = Buffer.alloc(20);
header.write('glTF');
header.writeUInt32LE(2, 4);
header.writeUInt32LE(28 + json.length + offset, 8);
header.writeUInt32LE(json.length, 12);
header.writeUInt32LE(0x4e4f534a, 16);
const binHeader = Buffer.alloc(8);
binHeader.writeUInt32LE(offset);
binHeader.writeUInt32LE(0x004e4942, 4);
const result = Buffer.concat([header, json, binHeader, ...buffers]);

const hash = crypto.createHash('sha256').update(result).digest('hex');
const filename = `jesus-v1-${hash.slice(0, 12)}.glb`;
await fs.mkdir(output, { recursive: true });
await fs.writeFile(path.join(output, filename), result);

const triangles = [0, 0];
for (const node of (gltf.nodes || []).filter((node) => node.mesh !== undefined)) {
  const lod = node.name?.includes('_LOD1') ? 1 : 0;
  for (const primitive of gltf.meshes[node.mesh].primitives || []) {
    if (primitive.indices === undefined) throw new Error(`${node.name}: indexed geometry is required`);
    triangles[lod] += gltf.accessors[primitive.indices].count / 3;
  }
}

const record = {
  id: 'human-jesus-v1',
  url: `/assets/scenes/shared/humans/${filename}`,
  size: result.length,
  hash: hash.slice(0, 8),
  sha256: hash,
  source: metadata.source,
  license: metadata.license,
  triangles,
};

await fs.writeFile(
  manifestPath,
  '// Generated by scripts/humans/package_jesus_hero.mjs.\n'
    + `export const HERO_MODEL_ASSETS = ${JSON.stringify([record], null, 2)};\n`,
);

console.log({ id: record.id, bytes: record.size, triangles: record.triangles, file: filename });
