// Optimize embedded PNGs without introducing runtime decoder dependencies.
// Rebuild buffer views on four-byte boundaries, then publish content hashes.
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import sharp from 'sharp';
const root = path.resolve(import.meta.dirname, '../..');
const cache = path.join(root, 'scripts/.cache/humans');
const output = path.join(root, 'public/assets/scenes/shared/humans');
const records = [];
for (const id of ['artisan', 'villager', 'traveler']) {
  const bytes = await fs.readFile(path.join(cache, `${id}.glb`));
  const jsonLength = bytes.readUInt32LE(12);
  const gltf = JSON.parse(bytes.subarray(20, 20 + jsonLength).toString());
  const binary = bytes.subarray(28 + jsonLength);
  const pngViews = new Set(gltf.images.filter((image) => image.mimeType === 'image/png').map((image) => image.bufferView));
  const buffers = []; let offset = 0;
  for (const [index, view] of gltf.bufferViews.entries()) {
    let data = binary.subarray(view.byteOffset || 0, (view.byteOffset || 0) + view.byteLength);
    if (pngViews.has(index)) data = await sharp(data).png({ palette: true, colours: 256, effort: 10 }).toBuffer();
    view.byteOffset = offset; view.byteLength = data.length;
    buffers.push(data); offset += data.length;
    const padding = (4 - offset % 4) % 4;
    if (padding) { buffers.push(Buffer.alloc(padding)); offset += padding; }
  }
  gltf.buffers[0].byteLength = offset;
  // glTF alpha cutouts render hair reliably without per-card transparency sorting.
  for (const material of gltf.materials) {
    if (/Hair|Brows|Beard/i.test(material.name)) {
      material.alphaMode = 'MASK'; material.alphaCutoff = 0.4;
    }
  }
  gltf.asset.extras = { source: 'MakeHuman Community CC0 assets', provenance: 'docs/scene-humans-assets.md',
    authoring: 'Blender 5.1 / MPFB2; Miqra Kodesh character adaptations',
    historicalStatus: 'Interpretive background people, not portraits or verified period costume replicas' };
  const rawJson = Buffer.from(JSON.stringify(gltf));
  const json = Buffer.concat([rawJson, Buffer.alloc((4 - rawJson.length % 4) % 4, 32)]);
  const header = Buffer.alloc(20); header.write('glTF'); header.writeUInt32LE(2, 4);
  header.writeUInt32LE(28 + json.length + offset, 8); header.writeUInt32LE(json.length, 12); header.writeUInt32LE(0x4e4f534a, 16);
  const binHeader = Buffer.alloc(8); binHeader.writeUInt32LE(offset); binHeader.writeUInt32LE(0x004e4942, 4);
  const result = Buffer.concat([header, json, binHeader, ...buffers]);
  const hash = crypto.createHash('sha256').update(result).digest('hex');
  const filename = `${id}-${hash.slice(0, 12)}.glb`;
  await fs.writeFile(path.join(output, filename), result);
  const triangles = [0, 0];
  for (const node of gltf.nodes.filter((node) => node.mesh !== undefined)) {
    const lod = node.name.includes('_LOD1') ? 1 : 0;
    for (const primitive of gltf.meshes[node.mesh].primitives) triangles[lod] += gltf.accessors[primitive.indices].count / 3;
  }
  records.push({ id: `human-${id}`, url: `/assets/scenes/shared/humans/${filename}`, size: result.length,
    hash: hash.slice(0, 8), sha256: hash, source: 'makehuman-community-cc0', license: 'CC0', triangles });
}
await fs.writeFile(path.join(root, 'src/components/scene/sceneHumanAssets.js'),
  '// Generated by scripts/humans/package_characters.mjs. Source notices accompany the GLBs.\n' +
  `export const HUMAN_MODEL_ASSETS = ${JSON.stringify(records, null, 2)};\n`);
console.log(records.map(({ id, size, triangles }) => ({ id, bytes: size, triangles })));
