"""Prepare the recorded scene sounds (Python 3 + ffmpeg, no Python packages).

Usage: python3 scripts/prepare-scene-audio.py /path/to/extracted/source/packs
Source downloads and licenses: public/assets/scenes/shared/audio/CREDITS.txt.
Keep the archive directory names when extracting; name VistulaShort_0.mp3
waves.mp3 and extract Kenney's Impact Sounds into impact/.
"""

import array
import hashlib
import json
import math
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path(sys.argv[1])
OUTPUT = ROOT / 'public/assets/scenes/shared/audio'
RATE = 44100
FFMPEG = str(ROOT / 'node_modules/ffmpeg-static/ffmpeg')
assets = []


def prepare(name, relative, *, kind, credit, license, surface=None, start=0, seconds=None):
    command = [FFMPEG, '-v', 'error', '-ss', str(start), '-i', str(SOURCE / relative)]
    if seconds:
        command += ['-t', str(seconds)]
    command += ['-af', 'highpass=f=80,lowpass=f=9500', '-ac', '1', '-ar', str(RATE), '-f', 'f32le', '-']
    samples = array.array('f', subprocess.check_output(command))
    if sys.byteorder != 'little':
        samples.byteswap()

    if kind == 'loop':
        # Overlap the tail with the head, then rotate. Both the join and the
        # wrap are continuous; there is no dip to silence on each repetition.
        overlap = min(round(RATE * 0.5), len(samples) // 5)
        seam = array.array('f', (
            samples[-overlap + i] * (1 - i / (overlap - 1))
            + samples[i] * i / (overlap - 1) for i in range(overlap)
        ))
        samples = samples[overlap:-overlap] + seam
    else:
        attack, release = round(RATE * 0.002), round(RATE * 0.025)
        for i in range(min(attack, len(samples))):
            samples[i] *= i / attack
        for i in range(min(release, len(samples))):
            samples[-1 - i] *= i / release

    rms = math.sqrt(sum(x * x for x in samples) / len(samples))
    gain = min(0.1 / max(rms, 1e-9), 0.5 / max(abs(x) for x in samples))
    samples = array.array('f', (x * gain for x in samples))
    if sys.byteorder != 'little':
        samples.byteswap()
    encoded = subprocess.check_output([
        FFMPEG, '-v', 'error', '-f', 'f32le', '-ar', str(RATE), '-ac', '1', '-i', '-',
        '-fflags', '+bitexact', '-flags:a', '+bitexact', '-c:a', 'libvorbis', '-q:a', '4', '-f', 'ogg', '-',
    ], input=samples.tobytes())
    digest = hashlib.sha256(encoded).hexdigest()[:8]
    filename = f'{name}-{digest}.ogg'
    OUTPUT.mkdir(parents=True, exist_ok=True)
    (OUTPUT / filename).write_bytes(encoded)
    definition = dict(id=f'snd-{name}', url=f'/assets/scenes/shared/audio/{filename}',
                      size=len(encoded), hash=digest, type=kind, source=credit, license=license,
                      original=relative)
    if surface:
        definition['surface'] = surface
    assets.append(definition)


for surface, source_name in [('stone', 'Stone'), ('sand', 'Sand')]:
    for index, side in enumerate(['L1', 'R1', 'L2', 'R2', 'L3', 'R3'], 1):
        prepare(f'step-{surface}-{index}', f'Fantozzi-footsteps/flac/Fantozzi-{source_name}{side}.flac',
                kind='step', surface=surface, credit='Fantozzi / qubodup', license='CC0')

for surface, source_name in [('earth', 'grass'), ('timber', 'wood')]:
    for index in range(4):
        prepare(f'step-{surface}-{index + 1}', f'impact/Audio/footstep_{source_name}_{index:03}.ogg',
                kind='step', surface=surface, credit='Kenney', license='CC0')

for index, side in enumerate(['l', 'r'], 1):
    prepare(f'step-water-{index}', f'sfx_step_water_{side}.flac', kind='step', surface='water',
            credit='Blender Foundation / Yo Frankie!', license='CC-BY-3.0')

prepare('wind', 'ambient_mountains_forest_river_waterfall_wind/amb_wind_1.flac',
        kind='loop', credit='Blender Foundation / Yo Frankie!', license='CC-BY-3.0')
prepare('shore', 'waves.mp3', kind='loop', credit='RandomMind', license='CC0', start=35, seconds=24)
prepare('surf', 'waves.mp3', kind='loop', credit='RandomMind', license='CC0', start=110, seconds=28)
prepare('fire', 'qubodupFireLoop.ogg', kind='loop', credit='qubodup', license='CC-BY-3.0')
for name, filename in [('bird-1', 'bird_1'), ('bird-2', 'bird_2'), ('cricket', 'cricket_1'), ('frog', 'frog_1')]:
    prepare(name, f'amb_bird_cricket_frog/amb_{filename}.flac', kind='call',
            credit='Blender Foundation / Yo Frankie!', license='CC-BY-3.0')

manifest = ROOT / 'src/components/scene/sceneAudioManifest.js'
manifest.write_text('// Recorded foley. Generated by scripts/prepare-scene-audio.py.\n'
                    '// Attribution: /assets/scenes/shared/audio/CREDITS.txt\n'
                    f'export const SCENE_AUDIO_ASSETS = {json.dumps(assets, indent=2)};\n')
print(f'Prepared {len(assets)} sounds, {sum(a["size"] for a in assets):,} bytes')
