-- Bible Wiki slice 1: community observations on foundation entries.
--
-- Foundation pages (people/places + their verse indexes) ship as a static
-- asset (src/assets/bible-wiki.json, regenerated by scripts/build-bible-wiki.js)
-- — the same Bible for every org, so no table needed. Observations are the
-- org-scoped community layer: every observation MUST cite at least one
-- scripture reference (enforced here, not just in the UI), starts as
-- 'pending', and gains the org-visible "confirmed" badge once a leader
-- reviews it. entry_slug keys into the static asset (e.g. 'aaron_1',
-- 'jerusalem'), so no FK.

create table public.wiki_observations (
  id              uuid        primary key default gen_random_uuid(),
  organization_id uuid        not null references public.organizations(id) on delete cascade,
  entry_slug      text        not null,
  user_id         uuid        not null references public.profiles(id) on delete cascade,
  content         text        not null check (char_length(content) between 1 and 2000),
  refs            text[]      not null check (coalesce(array_length(refs, 1), 0) between 1 and 10),
  status          text        not null default 'pending' check (status in ('pending', 'confirmed')),
  confirmed_by    uuid        references public.profiles(id) on delete set null,
  confirmed_at    timestamptz,
  created_at      timestamptz not null default now()
);

create index wiki_observations_org_entry_idx
  on public.wiki_observations (organization_id, entry_slug, created_at);

alter table public.wiki_observations enable row level security;

create policy "org members read wiki observations"
  on public.wiki_observations for select
  to authenticated
  using (public.is_developer() or organization_id = public.get_my_organization_id());

create policy "org members add wiki observations"
  on public.wiki_observations for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and organization_id = public.get_my_organization_id()
    and status = 'pending'
  );

-- Authors may edit their own observation only while it is pending, and cannot
-- self-confirm (with check keeps the row pending after the edit).
create policy "authors edit own pending wiki observations"
  on public.wiki_observations for update
  to authenticated
  using (user_id = auth.uid() and status = 'pending')
  with check (user_id = auth.uid() and status = 'pending');

create policy "leaders review wiki observations"
  on public.wiki_observations for update
  to authenticated
  using (public.is_leader() and organization_id = public.get_my_organization_id())
  with check (public.is_leader() and organization_id = public.get_my_organization_id());

create policy "authors and admins delete wiki observations"
  on public.wiki_observations for delete
  to authenticated
  using (
    user_id = auth.uid()
    or (public.is_admin() and organization_id = public.get_my_organization_id())
    or public.is_developer()
  );
